package datagrip

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// builtInMainKeyCipherKey is EncryptionSupport.kt's hardcoded AES key, spelled out byte by byte
// there and decoding to the ASCII string "Proxy Config Sec" (F7).
var builtInMainKeyCipherKey = []byte("Proxy Config Sec")

// maxMainKeyFileBytes bounds the read of c.pwd/pdb.pwd — both are a few hundred bytes in every
// real file; 1 MiB is a generous ceiling against a pathological path.
const maxMainKeyFileBytes = 1 << 20

// cPwdFields is mainKey.kt's MainKeyFileStorage.save output (F7): three top-level "key: value"
// lines, with `value`'s !!binary scalar either inline or SnakeYAML's folded/indented block style
// for a value long enough to wrap. A bespoke three-key parse, not a general YAML decode —
// IntelliJ's own SnakeYAML composer forces every scalar to Tag.STR here, which a standards-
// following YAML library would not reproduce (AGENTS.md: this is the "~150 lines of
// format-following code" F9 says has no library to reach for).
type cPwdFields struct {
	Encryption      string
	IsAutoGenerated string
	ValueBase64     string
}

func parseCPwd(data []byte) cPwdFields {
	var fields cPwdFields
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	i := 0
	for i < len(lines) {
		line := lines[i]
		if strings.TrimLeft(line, " \t") != line {
			// Indented with nothing above it having opened a block — stray content, skip.
			i++
			continue
		}
		key, rest, ok := strings.Cut(line, ":")
		if !ok {
			i++
			continue
		}
		key = strings.TrimSpace(key)
		rest = strings.TrimSpace(rest)
		switch key {
		case "encryption":
			fields.Encryption = strings.Trim(rest, `"'`)
			i++
		case "isAutoGenerated":
			fields.IsAutoGenerated = rest
			i++
		case "value":
			rest = strings.TrimSpace(strings.TrimPrefix(rest, "!!binary"))
			i++
			if rest != "" && rest != "|" && rest != "|-" && rest != ">" && rest != ">-" {
				fields.ValueBase64 = rest
				continue
			}
			// Block scalar (SnakeYAML folds a long base64 value across indented continuation
			// lines): consume every following indented (or blank) line as part of it.
			var b strings.Builder
			for i < len(lines) {
				next := lines[i]
				if strings.TrimSpace(next) == "" {
					i++
					continue
				}
				if strings.TrimLeft(next, " \t") == next {
					break
				}
				b.WriteString(strings.TrimSpace(next))
				i++
			}
			fields.ValueBase64 = b.String()
		default:
			i++
		}
	}
	return fields
}

// ReadMainKey reads the PasswordSafe main key from dir/c.pwd, falling back to the legacy
// dir/pdb.pwd when c.pwd is absent (F7). The returned bytes are exactly what
// MainKeyFileStorage.save wrote before encryption — for an auto-generated key, itself base64
// ASCII text, used as-is as the KDBX composite-key passphrase (F8/F9), never base64-decoded a
// second time.
func ReadMainKey(dir string) ([]byte, error) {
	cPwdPath := filepath.Join(dir, "c.pwd")
	data, err := readBoundedFile(cPwdPath, maxMainKeyFileBytes)
	if err == nil {
		return decodeCPwd(data, cPwdPath)
	}
	if !os.IsNotExist(err) {
		return nil, err
	}

	pdbPwdPath := filepath.Join(dir, "pdb.pwd")
	data, err = readBoundedFile(pdbPwdPath, maxMainKeyFileBytes)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, &RefusalError{
				Code:    ReasonCredentialStoreNotFound,
				Message: fmt.Sprintf("neither c.pwd nor the legacy pdb.pwd exists in %s", dir),
			}
		}
		return nil, err
	}
	// F7: "the legacy pdb.pwd file is the *raw* blob with no YAML wrapper, decrypted with the
	// same built-in key" — there is no encryption: field to read, so it is only ever tried as
	// BUILT_IN.
	return decryptBuiltIn(data, pdbPwdPath)
}

func readBoundedFile(path string, max int64) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	limited := io.LimitReader(f, max+1)
	data, err := io.ReadAll(limited)
	if err != nil {
		return nil, err
	}
	if int64(len(data)) > max {
		return nil, fmt.Errorf("datagrip: %s is implausibly large", path)
	}
	return data, nil
}

func decodeCPwd(data []byte, path string) ([]byte, error) {
	fields := parseCPwd(data)
	switch fields.Encryption {
	case "", "BUILT_IN":
		// ok — BUILT_IN is the default when the field is somehow absent.
	case "CRYPT_32":
		return nil, &RefusalError{
			Code: ReasonCredentialStoreUnsupported,
			Message: fmt.Sprintf(
				"c.pwd in %s uses CRYPT_32 encryption (Windows DPAPI), which Kira Studio cannot read on this platform.",
				filepath.Dir(path)),
		}
	case "PGP_KEY":
		return nil, &RefusalError{
			Code: ReasonCredentialStoreUnsupported,
			Message: fmt.Sprintf(
				"c.pwd in %s uses PGP_KEY encryption, which Kira Studio cannot read.",
				filepath.Dir(path)),
		}
	default:
		return nil, &RefusalError{
			Code: ReasonCredentialStoreUnsupported,
			Message: fmt.Sprintf(
				"c.pwd in %s uses an unrecognised encryption type %q, which Kira Studio cannot read.",
				filepath.Dir(path), fields.Encryption),
		}
	}

	raw, err := base64.StdEncoding.DecodeString(fields.ValueBase64)
	if err != nil {
		return nil, mainKeyDecryptFailure(path)
	}
	return decryptBuiltIn(raw, path)
}

func mainKeyDecryptFailure(path string) error {
	return &RefusalError{
		Code: ReasonCredentialStoreUnsupported,
		Message: fmt.Sprintf(
			"could not decrypt the PasswordSafe main key in %s — this DataGrip/IDE version may store it differently.",
			path),
	}
}

// decryptBuiltIn is F7's AesEncryptionSupport: AES/CBC/PKCS5Padding under the hardcoded
// "Proxy Config Sec" key, over a 4-byte-big-endian-IV-length ‖ IV ‖ ciphertext envelope.
func decryptBuiltIn(envelope []byte, path string) ([]byte, error) {
	if len(envelope) < 4 {
		return nil, mainKeyDecryptFailure(path)
	}
	ivLen := int(binary.BigEndian.Uint32(envelope[:4]))
	// D12/case 15: an IV length other than AES's own 16-byte block size is never valid here —
	// refused by name, never passed to cipher.NewCBCDecrypter to fail some other way.
	if ivLen != aes.BlockSize || len(envelope) < 4+ivLen {
		return nil, mainKeyDecryptFailure(path)
	}
	iv := envelope[4 : 4+ivLen]
	ciphertext := envelope[4+ivLen:]
	if len(ciphertext) == 0 || len(ciphertext)%aes.BlockSize != 0 {
		return nil, mainKeyDecryptFailure(path)
	}

	block, err := aes.NewCipher(builtInMainKeyCipherKey)
	if err != nil {
		return nil, mainKeyDecryptFailure(path)
	}
	plain := make([]byte, len(ciphertext))
	cipher.NewCBCDecrypter(block, iv).CryptBlocks(plain, ciphertext)

	unpadded, err := pkcs5Unpad(plain)
	if err != nil {
		return nil, mainKeyDecryptFailure(path)
	}
	return unpadded, nil
}

func pkcs5Unpad(data []byte) ([]byte, error) {
	if len(data) == 0 {
		return nil, fmt.Errorf("datagrip: empty plaintext")
	}
	padLen := int(data[len(data)-1])
	if padLen == 0 || padLen > aes.BlockSize || padLen > len(data) {
		return nil, fmt.Errorf("datagrip: invalid PKCS5 padding")
	}
	for _, b := range data[len(data)-padLen:] {
		if int(b) != padLen {
			return nil, fmt.Errorf("datagrip: invalid PKCS5 padding")
		}
	}
	return data[:len(data)-padLen], nil
}
