// Generated by tests/ipc/sqs/sqs.backend.spec.ts with
// KIRA_IPC_FIXTURES=write — do not hand-edit (P50 D5). The backend spec asserts every run's
// real response against this file; the frontend spec mocks the IPC layer with the exact same
// file. That is the split's anti-drift rule: a frontend spec cannot mock a shape the backend
// has stopped producing without this file's own backend assertion failing first.
import type { ControlSnapshot, PortSnapshot } from '../support/types';

export const controlSnapshots: ControlSnapshot[] = [
  {
    channel: 'kira:connections:list',
    response: [
      {
        id: 'test-sqs',
        sortOrder: 0,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z',
        name: 'Test SQS',
        kind: 'sqs',
        color: 'amber',
        mode: 'uri',
        readOnly: false,
        host: 'fixture-host',
        port: 0,
        database: null,
        username: null,
        uri: 'sqs://test:test@us-east-1',
        options: {
          endpoint: 'http://fixture-host:0',
        },
        preconnect: null,
        preconnectSidecar: false,
      },
    ],
  },
  {
    channel: 'kira:connections:states',
    response: [],
  },
  {
    channel: 'kira:connections:connect',
    args: {
      id: 'test-sqs',
    },
    response: {
      connectionId: 'test-sqs',
      status: 'connected',
      serverVersion: 'Amazon SQS',
      error: null,
      since: 0,
      caps: {
        tabular: false,
        documents: false,
        keyValue: false,
        stream: true,
        keyBrowser: false,
        defaultPageKind: 'stream',
        sql: false,
        definition: true,
        describe: false,
        projection: false,
        serverFilter: false,
        exactCount: false,
        pagination: 'batch',
        foreignKeys: false,
        canInsert: true,
        canUpdate: false,
        canDelete: true,
        writable: true,
        transactions: false,
        cancel: true,
        fileTransfer: false,
      },
    },
  },
  {
    channel: 'kira:ops:recent',
    response: [],
  },
  {
    channel: 'kira:tree:children',
    args: {
      connectionId: 'test-sqs',
      path: '',
      refresh: false,
    },
    response: {
      nodes: [
        {
          kind: 'queue',
          name: 'drain-queue',
          path: 'queue:drain-queue',
          hasChildren: false,
        },
        {
          kind: 'queue',
          name: 'empty-queue',
          path: 'queue:empty-queue',
          hasChildren: false,
        },
        {
          kind: 'queue',
          name: 'orders-queue',
          path: 'queue:orders-queue',
          hasChildren: false,
        },
      ],
      source: 'server',
      truncated: false,
    },
  },
  {
    channel: 'kira:tree:definition',
    args: {
      connectionId: 'test-sqs',
      path: 'queue:orders-queue',
      tabId: null,
    },
    response: {
      definition: {
        path: 'queue:orders-queue',
        kind: 'queue',
        qualifiedName: 'orders-queue',
        language: 'json',
        statements: [
          '{\n  "ApproximateNumberOfMessages": "0",\n  "ApproximateNumberOfMessagesNotVisible": "5",\n  "ApproximateNumberOfMessagesDelayed": "0",\n  "CreatedTimestamp": "1700000000",\n  "DelaySeconds": "0",\n  "LastModifiedTimestamp": "1700000000",\n  "MaximumMessageSize": "262144",\n  "MessageRetentionPeriod": "345600",\n  "QueueArn": "arn:aws:sqs:us-east-1:170000000000:orders-queue",\n  "ReceiveMessageWaitTimeSeconds": "0",\n  "VisibilityTimeout": "30",\n  "SqsManagedSseEnabled": "true"\n}',
        ],
        origin: 'server',
        notes: [],
        constraints: [],
        documentSchema: null,
        sections: [
          {
            title: 'Attributes',
            rows: [
              {
                name: 'ApproximateNumberOfMessages',
                value: '0',
                detail: null,
              },
              {
                name: 'ApproximateNumberOfMessagesDelayed',
                value: '0',
                detail: null,
              },
              {
                name: 'ApproximateNumberOfMessagesNotVisible',
                value: '5',
                detail: null,
              },
              {
                name: 'CreatedTimestamp',
                value: '1700000000',
                detail: null,
              },
              {
                name: 'DelaySeconds',
                value: '0',
                detail: null,
              },
              {
                name: 'LastModifiedTimestamp',
                value: '1700000000',
                detail: null,
              },
              {
                name: 'MaximumMessageSize',
                value: '262144',
                detail: null,
              },
              {
                name: 'MessageRetentionPeriod',
                value: '345600',
                detail: null,
              },
              {
                name: 'QueueArn',
                value: 'arn:aws:sqs:us-east-1:000000000000:orders-queue',
                detail: null,
              },
              {
                name: 'ReceiveMessageWaitTimeSeconds',
                value: '0',
                detail: null,
              },
              {
                name: 'SqsManagedSseEnabled',
                value: 'true',
                detail: null,
              },
              {
                name: 'VisibilityTimeout',
                value: '30',
                detail: null,
              },
            ],
          },
        ],
        generatedAt: '2024-01-01T00:00:00.000Z',
      },
      source: 'server',
    },
  },
  {
    channel: 'kira:tree:definition',
    args: {
      connectionId: 'test-sqs',
      path: 'queue:orders-queue',
      refresh: true,
      tabId: null,
    },
    response: {
      definition: {
        path: 'queue:orders-queue',
        kind: 'queue',
        qualifiedName: 'orders-queue',
        language: 'json',
        statements: [
          '{\n  "ApproximateNumberOfMessages": "0",\n  "ApproximateNumberOfMessagesNotVisible": "5",\n  "ApproximateNumberOfMessagesDelayed": "0",\n  "CreatedTimestamp": "1700000000",\n  "DelaySeconds": "0",\n  "LastModifiedTimestamp": "1700000000",\n  "MaximumMessageSize": "262144",\n  "MessageRetentionPeriod": "345600",\n  "QueueArn": "arn:aws:sqs:us-east-1:170000000000:orders-queue",\n  "ReceiveMessageWaitTimeSeconds": "0",\n  "VisibilityTimeout": "30",\n  "SqsManagedSseEnabled": "true"\n}',
        ],
        origin: 'server',
        notes: [],
        constraints: [],
        documentSchema: null,
        sections: [
          {
            title: 'Attributes',
            rows: [
              {
                name: 'ApproximateNumberOfMessages',
                value: '0',
                detail: null,
              },
              {
                name: 'ApproximateNumberOfMessagesDelayed',
                value: '0',
                detail: null,
              },
              {
                name: 'ApproximateNumberOfMessagesNotVisible',
                value: '5',
                detail: null,
              },
              {
                name: 'CreatedTimestamp',
                value: '1700000000',
                detail: null,
              },
              {
                name: 'DelaySeconds',
                value: '0',
                detail: null,
              },
              {
                name: 'LastModifiedTimestamp',
                value: '1700000000',
                detail: null,
              },
              {
                name: 'MaximumMessageSize',
                value: '262144',
                detail: null,
              },
              {
                name: 'MessageRetentionPeriod',
                value: '345600',
                detail: null,
              },
              {
                name: 'QueueArn',
                value: 'arn:aws:sqs:us-east-1:000000000000:orders-queue',
                detail: null,
              },
              {
                name: 'ReceiveMessageWaitTimeSeconds',
                value: '0',
                detail: null,
              },
              {
                name: 'SqsManagedSseEnabled',
                value: 'true',
                detail: null,
              },
              {
                name: 'VisibilityTimeout',
                value: '30',
                detail: null,
              },
            ],
          },
        ],
        generatedAt: '2024-01-01T00:00:00.000Z',
      },
      source: 'server',
    },
  },
];

export const portSnapshots: PortSnapshot[] = [
  {
    op: 'data:read',
    payload: {
      opId: 'be-poll-orders',
      tabId: null,
      connectionId: 'test-sqs',
      path: 'queue:orders-queue',
      projection: null,
      filter: null,
      sort: null,
      pageSize: 100,
      cursor: {
        mode: 'offset',
        offset: 0,
      },
    },
    response: {
      kind: 'read',
      page: {
        kind: 'stream',
        keys: ['msg-0', 'msg-1', 'msg-2', 'msg-3', 'msg-4'],
        headers: [
          '{"source":{"DataType":"String","StringValue":"seed"}}',
          '{"source":{"DataType":"String","StringValue":"seed"}}',
          '{"source":{"DataType":"String","StringValue":"seed"}}',
          '{"source":{"DataType":"String","StringValue":"seed"}}',
          '{"source":{"DataType":"String","StringValue":"seed"}}',
        ],
        attrs: [
          '{"SenderId":"000000000000","SentTimestamp":"1700000000000","ApproximateReceiveCount":"1","ApproximateFirstReceiveTimestamp":"1700000000000"}',
          '{"SenderId":"000000000000","SentTimestamp":"1700000000000","ApproximateReceiveCount":"1","ApproximateFirstReceiveTimestamp":"1700000000000"}',
          '{"SenderId":"000000000000","SentTimestamp":"1700000000000","ApproximateReceiveCount":"1","ApproximateFirstReceiveTimestamp":"1700000000000"}',
          '{"SenderId":"000000000000","SentTimestamp":"1700000000000","ApproximateReceiveCount":"1","ApproximateFirstReceiveTimestamp":"1700000000000"}',
          '{"SenderId":"000000000000","SentTimestamp":"1700000000000","ApproximateReceiveCount":"1","ApproximateFirstReceiveTimestamp":"1700000000000"}',
        ],
        timestamps: [
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
        ],
        bodies: ['{"seq":0}', '{"seq":1}', '{"seq":2}', '{"seq":3}', '{"seq":4}'],
        position: {
          offset: null,
          pageSize: 100,
          hasMore: false,
          nextToken: null,
          prevToken: null,
          strategy: 'batch',
        },
        visibilityTimeoutSeconds: 30,
      },
      source: 'server',
    },
  },
  {
    op: 'data:invalidate',
    payload: {
      connectionId: 'test-sqs',
      path: 'queue:orders-queue',
    },
    response: {
      kind: 'invalidate',
    },
  },
  {
    op: 'data:count',
    payload: {
      opId: 'be-count-empty',
      tabId: null,
      connectionId: 'test-sqs',
      path: 'queue:empty-queue',
      filter: null,
    },
    response: {
      kind: 'count',
      value: 0,
      exact: false,
      stale: false,
      source: 'server',
    },
  },
];
