// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gitwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DecorationRef struct {
	_tab flatbuffers.Table
}

func GetRootAsDecorationRef(buf []byte, offset flatbuffers.UOffsetT) *DecorationRef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DecorationRef{}
	x.Init(buf, n+offset)
	return x
}

func FinishDecorationRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDecorationRef(buf []byte, offset flatbuffers.UOffsetT) *DecorationRef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DecorationRef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDecorationRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DecorationRef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DecorationRef) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DecorationRef) Kind() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecorationRef) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecorationRef) IsHead() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DecorationRef) MutateIsHead(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func DecorationRefStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DecorationRefAddKind(builder *flatbuffers.Builder, kind flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(kind), 0)
}
func DecorationRefAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func DecorationRefAddIsHead(builder *flatbuffers.Builder, isHead bool) {
	builder.PrependBoolSlot(2, isHead, false)
}
func DecorationRefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
