// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gitwire

import "strconv"

type Payload byte

const (
	PayloadNONE              Payload = 0
	PayloadPackedCommitChunk Payload = 1
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:              "NONE",
	PayloadPackedCommitChunk: "PackedCommitChunk",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":              PayloadNONE,
	"PackedCommitChunk": PayloadPackedCommitChunk,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
