// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gitwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RowDecorations struct {
	_tab flatbuffers.Table
}

func GetRootAsRowDecorations(buf []byte, offset flatbuffers.UOffsetT) *RowDecorations {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RowDecorations{}
	x.Init(buf, n+offset)
	return x
}

func FinishRowDecorationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRowDecorations(buf []byte, offset flatbuffers.UOffsetT) *RowDecorations {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RowDecorations{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRowDecorationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RowDecorations) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RowDecorations) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RowDecorations) Row() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RowDecorations) MutateRow(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *RowDecorations) Refs(obj *DecorationRef, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RowDecorations) RefsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RowDecorationsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RowDecorationsAddRow(builder *flatbuffers.Builder, row uint32) {
	builder.PrependUint32Slot(0, row, 0)
}
func RowDecorationsAddRefs(builder *flatbuffers.Builder, refs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(refs), 0)
}
func RowDecorationsStartRefsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RowDecorationsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
