package ipcfixture

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// FixtureWriteEnv is capture.ts's FIXTURE_WRITE_ENV, ported verbatim (P58f §4.6/D15) so the muscle
// memory and the AGENTS.md line survive the port unchanged.
const FixtureWriteEnv = "KIRA_IPC_FIXTURES"

// IsWriteMode is capture.ts's isFixtureWriteMode.
func IsWriteMode() bool {
	return os.Getenv(FixtureWriteEnv) == "write"
}

// mustMarshalNoEscape is every marshal call in this package's own primitive: Go's encoding/json
// escapes <, > and & by default, which would corrupt the SQL and JSON text these fixtures carry
// (write.go's first documented trap, P58f §4.3(c)). json.Encoder with SetEscapeHTML(false) is the
// fix; Encoder appends a trailing newline of its own, trimmed here so callers get exactly what
// json.Marshal would have, minus the escaping.
func mustMarshalNoEscape(v any) []byte {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		panic(fmt.Sprintf("ipcfixture: marshal: %v", err))
	}
	return bytes.TrimRight(buf.Bytes(), "\n")
}

// marshalIndentNoEscape is json.MarshalIndent with HTML-escaping disabled — write.go's third trap
// (§4.3(c)) forgives the remaining formatting drift from JSON.stringify(v, null, 2): biome
// normalises it, exactly as it already does for the TypeScript writer's own output.
func marshalIndentNoEscape(v any, prefix, indent string) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent(prefix, indent)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return bytes.TrimRight(buf.Bytes(), "\n"), nil
}

// FixturePathFor is capture.ts's fixturePathFor, rooted at repoRoot instead of process.cwd() (this
// package has no equivalent convention — every _test.go file passes its own adapter name).
func FixturePathFor(repoRoot, adapterName string) string {
	return filepath.Join(repoRoot, "apps", "kira-studio", "tests", "ipc", adapterName, adapterName+".fixture.ts")
}

// WriteFixtureModule is capture.ts's writeFixtureModule: the same header, the same two `export
// const` declarations, its provenance line naming this package instead of the TypeScript spec that
// used to write it (P58f §4.3(c)).
func WriteFixtureModule(filePath, adapterName string, control []ControlSnapshot, port []PortSnapshot) error {
	header := fmt.Sprintf(
		"// Generated by apps/kira-studio/internal/ipcfixture/%s_test.go with\n"+
			"// KIRA_IPC_FIXTURES=write — do not hand-edit (P50 D5). The backend spec asserts every run's\n"+
			"// real response against this file; the frontend spec mocks the IPC layer with the exact same\n"+
			"// file. That is the split's anti-drift rule: a frontend spec cannot mock a shape the backend\n"+
			"// has stopped producing without this file's own backend assertion failing first.\n"+
			"import type { ControlSnapshot, PortSnapshot } from '../support/types';\n",
		adapterName,
	)

	controlJSON, err := marshalIndentNoEscape(control, "", "  ")
	if err != nil {
		return fmt.Errorf("ipcfixture: marshal control snapshots: %w", err)
	}
	portJSON, err := marshalIndentNoEscape(port, "", "  ")
	if err != nil {
		return fmt.Errorf("ipcfixture: marshal port snapshots: %w", err)
	}

	body := fmt.Sprintf(
		"\nexport const controlSnapshots: ControlSnapshot[] = %s;\n\nexport const portSnapshots: PortSnapshot[] = %s;\n",
		controlJSON, portJSON,
	)

	return os.WriteFile(filePath, []byte(header+body), 0o644)
}
