// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CacheStats {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CacheStats {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCacheStats(bb:flatbuffers.ByteBuffer, obj?:CacheStats):CacheStats {
  return (obj || new CacheStats()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCacheStats(bb:flatbuffers.ByteBuffer, obj?:CacheStats):CacheStats {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CacheStats()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

l2Bytes():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

l2BudgetBytes():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

l2Entries():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

l2Hits():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

l2Misses():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

l3Entries():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startCacheStats(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addL2Bytes(builder:flatbuffers.Builder, l2Bytes:number) {
  builder.addFieldFloat64(0, l2Bytes, 0.0);
}

static addL2BudgetBytes(builder:flatbuffers.Builder, l2BudgetBytes:number) {
  builder.addFieldFloat64(1, l2BudgetBytes, 0.0);
}

static addL2Entries(builder:flatbuffers.Builder, l2Entries:number) {
  builder.addFieldInt32(2, l2Entries, 0);
}

static addL2Hits(builder:flatbuffers.Builder, l2Hits:number) {
  builder.addFieldInt32(3, l2Hits, 0);
}

static addL2Misses(builder:flatbuffers.Builder, l2Misses:number) {
  builder.addFieldInt32(4, l2Misses, 0);
}

static addL3Entries(builder:flatbuffers.Builder, l3Entries:number) {
  builder.addFieldInt32(5, l3Entries, 0);
}

static endCacheStats(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCacheStats(builder:flatbuffers.Builder, l2Bytes:number, l2BudgetBytes:number, l2Entries:number, l2Hits:number, l2Misses:number, l3Entries:number):flatbuffers.Offset {
  CacheStats.startCacheStats(builder);
  CacheStats.addL2Bytes(builder, l2Bytes);
  CacheStats.addL2BudgetBytes(builder, l2BudgetBytes);
  CacheStats.addL2Entries(builder, l2Entries);
  CacheStats.addL2Hits(builder, l2Hits);
  CacheStats.addL2Misses(builder, l2Misses);
  CacheStats.addL3Entries(builder, l3Entries);
  return CacheStats.endCacheStats(builder);
}
}
