// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TypeClass } from '../wire/type-class.js';


export class ColumnDescriptor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ColumnDescriptor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsColumnDescriptor(bb:flatbuffers.ByteBuffer, obj?:ColumnDescriptor):ColumnDescriptor {
  return (obj || new ColumnDescriptor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsColumnDescriptor(bb:flatbuffers.ByteBuffer, obj?:ColumnDescriptor):ColumnDescriptor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ColumnDescriptor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

dataType():string|null
dataType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dataType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typeClass():TypeClass {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TypeClass.number;
}

nullable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isPrimaryKey():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

generated():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startColumnDescriptor(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addDataType(builder:flatbuffers.Builder, dataTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataTypeOffset, 0);
}

static addTypeClass(builder:flatbuffers.Builder, typeClass:TypeClass) {
  builder.addFieldInt8(2, typeClass, TypeClass.number);
}

static addNullable(builder:flatbuffers.Builder, nullable:boolean) {
  builder.addFieldInt8(3, +nullable, +false);
}

static addIsPrimaryKey(builder:flatbuffers.Builder, isPrimaryKey:boolean) {
  builder.addFieldInt8(4, +isPrimaryKey, +false);
}

static addGenerated(builder:flatbuffers.Builder, generated:boolean) {
  builder.addFieldInt8(5, +generated, +false);
}

static endColumnDescriptor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  builder.requiredField(offset, 6) // data_type
  return offset;
}

static createColumnDescriptor(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, dataTypeOffset:flatbuffers.Offset, typeClass:TypeClass, nullable:boolean, isPrimaryKey:boolean, generated:boolean):flatbuffers.Offset {
  ColumnDescriptor.startColumnDescriptor(builder);
  ColumnDescriptor.addName(builder, nameOffset);
  ColumnDescriptor.addDataType(builder, dataTypeOffset);
  ColumnDescriptor.addTypeClass(builder, typeClass);
  ColumnDescriptor.addNullable(builder, nullable);
  ColumnDescriptor.addIsPrimaryKey(builder, isPrimaryKey);
  ColumnDescriptor.addGenerated(builder, generated);
  return ColumnDescriptor.endColumnDescriptor(builder);
}
}
