// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Source } from '../wire/source.js';


export class CountResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CountResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCountResponse(bb:flatbuffers.ByteBuffer, obj?:CountResponse):CountResponse {
  return (obj || new CountResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCountResponse(bb:flatbuffers.ByteBuffer, obj?:CountResponse):CountResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CountResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

exact():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

at():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

stale():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

source():Source {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Source.cache;
}

static startCountResponse(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat64(0, value, 0.0);
}

static addExact(builder:flatbuffers.Builder, exact:boolean) {
  builder.addFieldInt8(1, +exact, +false);
}

static addAt(builder:flatbuffers.Builder, at:number) {
  builder.addFieldFloat64(2, at, 0.0);
}

static addStale(builder:flatbuffers.Builder, stale:boolean) {
  builder.addFieldInt8(3, +stale, +false);
}

static addSource(builder:flatbuffers.Builder, source:Source) {
  builder.addFieldInt8(4, source, Source.cache);
}

static endCountResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCountResponse(builder:flatbuffers.Builder, value:number, exact:boolean, at:number, stale:boolean, source:Source):flatbuffers.Offset {
  CountResponse.startCountResponse(builder);
  CountResponse.addValue(builder, value);
  CountResponse.addExact(builder, exact);
  CountResponse.addAt(builder, at);
  CountResponse.addStale(builder, stale);
  CountResponse.addSource(builder, source);
  return CountResponse.endCountResponse(builder);
}
}
