// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Chunk } from '../wire/chunk.js';
import { PagePosition } from '../wire/page-position.js';


export class DocumentPage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DocumentPage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDocumentPage(bb:flatbuffers.ByteBuffer, obj?:DocumentPage):DocumentPage {
  return (obj || new DocumentPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDocumentPage(bb:flatbuffers.ByteBuffer, obj?:DocumentPage):DocumentPage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DocumentPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

position(obj?:PagePosition):PagePosition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PagePosition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

ids(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

bodies(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

rowCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

byteSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

fetchedAt():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startDocumentPage(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, positionOffset, 0);
}

static addIds(builder:flatbuffers.Builder, idsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idsOffset, 0);
}

static addBodies(builder:flatbuffers.Builder, bodiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, bodiesOffset, 0);
}

static addRowCount(builder:flatbuffers.Builder, rowCount:number) {
  builder.addFieldInt32(3, rowCount, 0);
}

static addByteSize(builder:flatbuffers.Builder, byteSize:number) {
  builder.addFieldFloat64(4, byteSize, 0.0);
}

static addFetchedAt(builder:flatbuffers.Builder, fetchedAt:number) {
  builder.addFieldFloat64(5, fetchedAt, 0.0);
}

static endDocumentPage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // position
  builder.requiredField(offset, 6) // ids
  builder.requiredField(offset, 8) // bodies
  return offset;
}

}
