// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Error } from '../wire/error.js';
import { FrameKind } from '../wire/frame-kind.js';
import { Payload, unionToPayload, unionListToPayload } from '../wire/payload.js';


export class Frame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Frame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFrame(bb:flatbuffers.ByteBuffer, obj?:Frame):Frame {
  return (obj || new Frame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFrame(bb:flatbuffers.ByteBuffer, obj?:Frame):Frame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Frame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('KIF1');
}

kind():FrameKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FrameKind.res;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

ok():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

topic():string|null
topic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
topic(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

error(obj?:Error):Error|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Error()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

payloadType():Payload {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Payload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startFrame(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addKind(builder:flatbuffers.Builder, kind:FrameKind) {
  builder.addFieldInt8(0, kind, FrameKind.res);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
}

static addOk(builder:flatbuffers.Builder, ok:boolean) {
  builder.addFieldInt8(2, +ok, +false);
}

static addTopic(builder:flatbuffers.Builder, topicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, topicOffset, 0);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, errorOffset, 0);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:Payload) {
  builder.addFieldInt8(5, payloadType, Payload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, payloadOffset, 0);
}

static endFrame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFrameBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'KIF1');
}

static finishSizePrefixedFrameBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'KIF1', true);
}

}
