// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Chunk } from '../wire/chunk.js';
import { PagePosition } from '../wire/page-position.js';
import { RedisType } from '../wire/redis-type.js';


export class KeyValuePage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):KeyValuePage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsKeyValuePage(bb:flatbuffers.ByteBuffer, obj?:KeyValuePage):KeyValuePage {
  return (obj || new KeyValuePage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsKeyValuePage(bb:flatbuffers.ByteBuffer, obj?:KeyValuePage):KeyValuePage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new KeyValuePage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

position(obj?:PagePosition):PagePosition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PagePosition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

redisType():RedisType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RedisType.string_;
}

ttlMs():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : null;
}

memoryBytes():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : null;
}

fields(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

values(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

rowCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

byteSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

fetchedAt():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startKeyValuePage(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, positionOffset, 0);
}

static addRedisType(builder:flatbuffers.Builder, redisType:RedisType) {
  builder.addFieldInt8(1, redisType, RedisType.string_);
}

static addTtlMs(builder:flatbuffers.Builder, ttlMs:number) {
  builder.addFieldFloat64(2, ttlMs, null);
}

static addMemoryBytes(builder:flatbuffers.Builder, memoryBytes:number) {
  builder.addFieldFloat64(3, memoryBytes, null);
}

static addFields(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, fieldsOffset, 0);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, valuesOffset, 0);
}

static addRowCount(builder:flatbuffers.Builder, rowCount:number) {
  builder.addFieldInt32(6, rowCount, 0);
}

static addByteSize(builder:flatbuffers.Builder, byteSize:number) {
  builder.addFieldFloat64(7, byteSize, 0.0);
}

static addFetchedAt(builder:flatbuffers.Builder, fetchedAt:number) {
  builder.addFieldFloat64(8, fetchedAt, 0.0);
}

static endKeyValuePage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // position
  builder.requiredField(offset, 12) // fields
  builder.requiredField(offset, 14) // values
  return offset;
}

}
