// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class MutateResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MutateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMutateResponse(bb:flatbuffers.ByteBuffer, obj?:MutateResponse):MutateResponse {
  return (obj || new MutateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMutateResponse(bb:flatbuffers.ByteBuffer, obj?:MutateResponse):MutateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MutateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

affectedRows():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMutateResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addAffectedRows(builder:flatbuffers.Builder, affectedRows:number) {
  builder.addFieldInt32(0, affectedRows, 0);
}

static endMutateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMutateResponse(builder:flatbuffers.Builder, affectedRows:number):flatbuffers.Offset {
  MutateResponse.startMutateResponse(builder);
  MutateResponse.addAffectedRows(builder, affectedRows);
  return MutateResponse.endMutateResponse(builder);
}
}
