// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ObjectDownloadResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ObjectDownloadResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsObjectDownloadResponse(bb:flatbuffers.ByteBuffer, obj?:ObjectDownloadResponse):ObjectDownloadResponse {
  return (obj || new ObjectDownloadResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsObjectDownloadResponse(bb:flatbuffers.ByteBuffer, obj?:ObjectDownloadResponse):ObjectDownloadResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ObjectDownloadResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bytes():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startObjectDownloadResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBytes(builder:flatbuffers.Builder, bytes:number) {
  builder.addFieldFloat64(0, bytes, 0.0);
}

static endObjectDownloadResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createObjectDownloadResponse(builder:flatbuffers.Builder, bytes:number):flatbuffers.Offset {
  ObjectDownloadResponse.startObjectDownloadResponse(builder);
  ObjectDownloadResponse.addBytes(builder, bytes);
  return ObjectDownloadResponse.endObjectDownloadResponse(builder);
}
}
