// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { DocumentPage } from '../wire/document-page.js';
import { KeyValuePage } from '../wire/key-value-page.js';
import { StreamPage } from '../wire/stream-page.js';
import { TabularPage } from '../wire/tabular-page.js';


export enum PageBody {
  NONE = 0,
  TabularPage = 1,
  DocumentPage = 2,
  KeyValuePage = 3,
  StreamPage = 4
}

export function unionToPageBody(
  type: PageBody,
  accessor: (obj:DocumentPage|KeyValuePage|StreamPage|TabularPage) => DocumentPage|KeyValuePage|StreamPage|TabularPage|null
): DocumentPage|KeyValuePage|StreamPage|TabularPage|null {
  switch(PageBody[type]) {
    case 'NONE': return null; 
    case 'TabularPage': return accessor(new TabularPage())! as TabularPage;
    case 'DocumentPage': return accessor(new DocumentPage())! as DocumentPage;
    case 'KeyValuePage': return accessor(new KeyValuePage())! as KeyValuePage;
    case 'StreamPage': return accessor(new StreamPage())! as StreamPage;
    default: return null;
  }
}

export function unionListToPageBody(
  type: PageBody, 
  accessor: (index: number, obj:DocumentPage|KeyValuePage|StreamPage|TabularPage) => DocumentPage|KeyValuePage|StreamPage|TabularPage|null, 
  index: number
): DocumentPage|KeyValuePage|StreamPage|TabularPage|null {
  switch(PageBody[type]) {
    case 'NONE': return null; 
    case 'TabularPage': return accessor(index, new TabularPage())! as TabularPage;
    case 'DocumentPage': return accessor(index, new DocumentPage())! as DocumentPage;
    case 'KeyValuePage': return accessor(index, new KeyValuePage())! as KeyValuePage;
    case 'StreamPage': return accessor(index, new StreamPage())! as StreamPage;
    default: return null;
  }
}
