// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Strategy } from '../wire/strategy.js';


export class PagePosition {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PagePosition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPagePosition(bb:flatbuffers.ByteBuffer, obj?:PagePosition):PagePosition {
  return (obj || new PagePosition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPagePosition(bb:flatbuffers.ByteBuffer, obj?:PagePosition):PagePosition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PagePosition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

offset():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : null;
}

pageSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

hasMore():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

nextToken():string|null
nextToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nextToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

prevToken():string|null
prevToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
prevToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

strategy():Strategy {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Strategy.keyset;
}

static startPagePosition(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addOffset(builder:flatbuffers.Builder, offset:number) {
  builder.addFieldInt32(0, offset, null);
}

static addPageSize(builder:flatbuffers.Builder, pageSize:number) {
  builder.addFieldInt32(1, pageSize, 0);
}

static addHasMore(builder:flatbuffers.Builder, hasMore:boolean) {
  builder.addFieldInt8(2, +hasMore, +false);
}

static addNextToken(builder:flatbuffers.Builder, nextTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nextTokenOffset, 0);
}

static addPrevToken(builder:flatbuffers.Builder, prevTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, prevTokenOffset, 0);
}

static addStrategy(builder:flatbuffers.Builder, strategy:Strategy) {
  builder.addFieldInt8(5, strategy, Strategy.keyset);
}

static endPagePosition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPagePosition(builder:flatbuffers.Builder, offset:number|null, pageSize:number, hasMore:boolean, nextTokenOffset:flatbuffers.Offset, prevTokenOffset:flatbuffers.Offset, strategy:Strategy):flatbuffers.Offset {
  PagePosition.startPagePosition(builder);
  if (offset !== null)
    PagePosition.addOffset(builder, offset);
  PagePosition.addPageSize(builder, pageSize);
  PagePosition.addHasMore(builder, hasMore);
  PagePosition.addNextToken(builder, nextTokenOffset);
  PagePosition.addPrevToken(builder, prevTokenOffset);
  PagePosition.addStrategy(builder, strategy);
  return PagePosition.endPagePosition(builder);
}
}
