// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PageBody, unionToPageBody, unionListToPageBody } from '../wire/page-body.js';


export class Page {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Page {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPage(bb:flatbuffers.ByteBuffer, obj?:Page):Page {
  return (obj || new Page()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPage(bb:flatbuffers.ByteBuffer, obj?:Page):Page {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Page()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bodyType():PageBody {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PageBody.NONE;
}

body<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startPage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBodyType(builder:flatbuffers.Builder, bodyType:PageBody) {
  builder.addFieldInt8(0, bodyType, PageBody.NONE);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bodyOffset, 0);
}

static endPage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPage(builder:flatbuffers.Builder, bodyType:PageBody, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  Page.startPage(builder);
  Page.addBodyType(builder, bodyType);
  Page.addBody(builder, bodyOffset);
  return Page.endPage(builder);
}
}
