// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CacheStats } from '../wire/cache-stats.js';
import { CountResponse } from '../wire/count-response.js';
import { EmptyResponse } from '../wire/empty-response.js';
import { ExecuteResponse } from '../wire/execute-response.js';
import { MutateResponse } from '../wire/mutate-response.js';
import { ObjectDownloadResponse } from '../wire/object-download-response.js';
import { PingPayload } from '../wire/ping-payload.js';
import { PreviewResponse } from '../wire/preview-response.js';
import { ReadResponse } from '../wire/read-response.js';


export enum Payload {
  NONE = 0,
  ReadResponse = 1,
  CountResponse = 2,
  PreviewResponse = 3,
  MutateResponse = 4,
  ExecuteResponse = 5,
  ObjectDownloadResponse = 6,
  PingPayload = 7,
  CacheStats = 8,
  EmptyResponse = 9
}

export function unionToPayload(
  type: Payload,
  accessor: (obj:CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse) => CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse|null
): CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse|null {
  switch(Payload[type]) {
    case 'NONE': return null; 
    case 'ReadResponse': return accessor(new ReadResponse())! as ReadResponse;
    case 'CountResponse': return accessor(new CountResponse())! as CountResponse;
    case 'PreviewResponse': return accessor(new PreviewResponse())! as PreviewResponse;
    case 'MutateResponse': return accessor(new MutateResponse())! as MutateResponse;
    case 'ExecuteResponse': return accessor(new ExecuteResponse())! as ExecuteResponse;
    case 'ObjectDownloadResponse': return accessor(new ObjectDownloadResponse())! as ObjectDownloadResponse;
    case 'PingPayload': return accessor(new PingPayload())! as PingPayload;
    case 'CacheStats': return accessor(new CacheStats())! as CacheStats;
    case 'EmptyResponse': return accessor(new EmptyResponse())! as EmptyResponse;
    default: return null;
  }
}

export function unionListToPayload(
  type: Payload, 
  accessor: (index: number, obj:CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse) => CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse|null, 
  index: number
): CacheStats|CountResponse|EmptyResponse|ExecuteResponse|MutateResponse|ObjectDownloadResponse|PingPayload|PreviewResponse|ReadResponse|null {
  switch(Payload[type]) {
    case 'NONE': return null; 
    case 'ReadResponse': return accessor(index, new ReadResponse())! as ReadResponse;
    case 'CountResponse': return accessor(index, new CountResponse())! as CountResponse;
    case 'PreviewResponse': return accessor(index, new PreviewResponse())! as PreviewResponse;
    case 'MutateResponse': return accessor(index, new MutateResponse())! as MutateResponse;
    case 'ExecuteResponse': return accessor(index, new ExecuteResponse())! as ExecuteResponse;
    case 'ObjectDownloadResponse': return accessor(index, new ObjectDownloadResponse())! as ObjectDownloadResponse;
    case 'PingPayload': return accessor(index, new PingPayload())! as PingPayload;
    case 'CacheStats': return accessor(index, new CacheStats())! as CacheStats;
    case 'EmptyResponse': return accessor(index, new EmptyResponse())! as EmptyResponse;
    default: return null;
  }
}
