// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PingPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PingPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPingPayload(bb:flatbuffers.ByteBuffer, obj?:PingPayload):PingPayload {
  return (obj || new PingPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPingPayload(bb:flatbuffers.ByteBuffer, obj?:PingPayload):PingPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PingPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pong():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

enginePid():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

at():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startPingPayload(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPong(builder:flatbuffers.Builder, pong:boolean) {
  builder.addFieldInt8(0, +pong, +false);
}

static addEnginePid(builder:flatbuffers.Builder, enginePid:number) {
  builder.addFieldInt32(1, enginePid, 0);
}

static addAt(builder:flatbuffers.Builder, at:number) {
  builder.addFieldFloat64(2, at, 0.0);
}

static endPingPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPingPayload(builder:flatbuffers.Builder, pong:boolean, enginePid:number, at:number):flatbuffers.Offset {
  PingPayload.startPingPayload(builder);
  PingPayload.addPong(builder, pong);
  PingPayload.addEnginePid(builder, enginePid);
  PingPayload.addAt(builder, at);
  return PingPayload.endPingPayload(builder);
}
}
