// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PreviewResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PreviewResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPreviewResponse(bb:flatbuffers.ByteBuffer, obj?:PreviewResponse):PreviewResponse {
  return (obj || new PreviewResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPreviewResponse(bb:flatbuffers.ByteBuffer, obj?:PreviewResponse):PreviewResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PreviewResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

statements(index: number):string
statements(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
statements(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

statementsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPreviewResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatements(builder:flatbuffers.Builder, statementsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, statementsOffset, 0);
}

static createStatementsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStatementsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPreviewResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // statements
  return offset;
}

static createPreviewResponse(builder:flatbuffers.Builder, statementsOffset:flatbuffers.Offset):flatbuffers.Offset {
  PreviewResponse.startPreviewResponse(builder);
  PreviewResponse.addStatements(builder, statementsOffset);
  return PreviewResponse.endPreviewResponse(builder);
}
}
