// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Page } from '../wire/page.js';
import { Source } from '../wire/source.js';


export class ReadResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadResponse(bb:flatbuffers.ByteBuffer, obj?:ReadResponse):ReadResponse {
  return (obj || new ReadResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadResponse(bb:flatbuffers.ByteBuffer, obj?:ReadResponse):ReadResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

page(obj?:Page):Page|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Page()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

source():Source {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Source.cache;
}

static startReadResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPage(builder:flatbuffers.Builder, pageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pageOffset, 0);
}

static addSource(builder:flatbuffers.Builder, source:Source) {
  builder.addFieldInt8(1, source, Source.cache);
}

static endReadResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // page
  return offset;
}

static createReadResponse(builder:flatbuffers.Builder, pageOffset:flatbuffers.Offset, source:Source):flatbuffers.Offset {
  ReadResponse.startReadResponse(builder);
  ReadResponse.addPage(builder, pageOffset);
  ReadResponse.addSource(builder, source);
  return ReadResponse.endReadResponse(builder);
}
}
