// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RedisType {
  string_ = 0,
  hash = 1,
  list = 2,
  set_ = 3,
  zset = 4,
  stream = 5,
  object = 6
}
