// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Strategy {
  keyset = 0,
  offset = 1,
  cursor = 2,
  offsetWindow = 3,
  batch = 4
}
