// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Chunk } from '../wire/chunk.js';
import { PagePosition } from '../wire/page-position.js';


export class StreamPage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamPage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamPage(bb:flatbuffers.ByteBuffer, obj?:StreamPage):StreamPage {
  return (obj || new StreamPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamPage(bb:flatbuffers.ByteBuffer, obj?:StreamPage):StreamPage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

position(obj?:PagePosition):PagePosition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PagePosition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

keys(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

headers(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

attrs(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

timestamps(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

bodies(obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

rowCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

byteSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

fetchedAt():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

visibilityTimeoutSeconds():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : null;
}

static startStreamPage(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, positionOffset, 0);
}

static addKeys(builder:flatbuffers.Builder, keysOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keysOffset, 0);
}

static addHeaders(builder:flatbuffers.Builder, headersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, headersOffset, 0);
}

static addAttrs(builder:flatbuffers.Builder, attrsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, attrsOffset, 0);
}

static addTimestamps(builder:flatbuffers.Builder, timestampsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, timestampsOffset, 0);
}

static addBodies(builder:flatbuffers.Builder, bodiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, bodiesOffset, 0);
}

static addRowCount(builder:flatbuffers.Builder, rowCount:number) {
  builder.addFieldInt32(6, rowCount, 0);
}

static addByteSize(builder:flatbuffers.Builder, byteSize:number) {
  builder.addFieldFloat64(7, byteSize, 0.0);
}

static addFetchedAt(builder:flatbuffers.Builder, fetchedAt:number) {
  builder.addFieldFloat64(8, fetchedAt, 0.0);
}

static addVisibilityTimeoutSeconds(builder:flatbuffers.Builder, visibilityTimeoutSeconds:number) {
  builder.addFieldInt32(9, visibilityTimeoutSeconds, null);
}

static endStreamPage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // position
  builder.requiredField(offset, 6) // keys
  builder.requiredField(offset, 8) // headers
  builder.requiredField(offset, 10) // attrs
  builder.requiredField(offset, 12) // timestamps
  builder.requiredField(offset, 14) // bodies
  return offset;
}

}
