// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Chunk } from '../wire/chunk.js';
import { ColumnDescriptor } from '../wire/column-descriptor.js';
import { PagePosition } from '../wire/page-position.js';


export class TabularPage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TabularPage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTabularPage(bb:flatbuffers.ByteBuffer, obj?:TabularPage):TabularPage {
  return (obj || new TabularPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTabularPage(bb:flatbuffers.ByteBuffer, obj?:TabularPage):TabularPage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TabularPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

columns(index: number, obj?:ColumnDescriptor):ColumnDescriptor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ColumnDescriptor()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

columnsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rowCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

chunks(index: number, obj?:Chunk):Chunk|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Chunk()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

chunksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

position(obj?:PagePosition):PagePosition|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PagePosition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

truncatedCells():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

byteSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

fetchedAt():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startTabularPage(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addColumns(builder:flatbuffers.Builder, columnsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, columnsOffset, 0);
}

static createColumnsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startColumnsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRowCount(builder:flatbuffers.Builder, rowCount:number) {
  builder.addFieldInt32(1, rowCount, 0);
}

static addChunks(builder:flatbuffers.Builder, chunksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, chunksOffset, 0);
}

static createChunksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChunksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, positionOffset, 0);
}

static addTruncatedCells(builder:flatbuffers.Builder, truncatedCells:number) {
  builder.addFieldInt32(4, truncatedCells, 0);
}

static addByteSize(builder:flatbuffers.Builder, byteSize:number) {
  builder.addFieldFloat64(5, byteSize, 0.0);
}

static addFetchedAt(builder:flatbuffers.Builder, fetchedAt:number) {
  builder.addFieldFloat64(6, fetchedAt, 0.0);
}

static endTabularPage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // columns
  builder.requiredField(offset, 8) // chunks
  builder.requiredField(offset, 10) // position
  return offset;
}

}
