// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TypeClass {
  number = 0,
  text = 1,
  boolean = 2,
  temporal = 3,
  binary = 4,
  json = 5,
  other = 6
}
