package mcpauth

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kirathecat/kira-studio/internal/mcpinstall"
)

// headerHelperScriptName is the fixed script name every DB MCP registration's own headersHelper
// points at (P108 Part 7 F2). Its content is a fixed template with no secret embedded — only the
// helper token file's own path, which is not itself sensitive — so it is written once and then
// left alone; EnsureHeaderHelperScript rewrites it unconditionally anyway (idempotent, cheap) so it
// self-heals if it is ever missing or a future version changes the template.
const headerHelperScriptName = "mcp-header-helper.sh"

// HeaderHelperScriptPath is EnsureHeaderHelperScript's own path, computed with no file I/O — a
// caller that already knows the script exists (statusFn's own repeated reads, once startFn has
// ensured it) can build the same path this way rather than re-writing the file on every read.
func HeaderHelperScriptPath(home string) string {
	return filepath.Join(home, headerHelperScriptName)
}

// EnsureHeaderHelperScript writes (or rewrites) the headersHelper script every DB MCP registration
// names — a plain shell script that reads tokenPath's own live plaintext at connection time and
// emits it as the `{"Authorization": "Bearer ..."}` JSON object Claude Code's headersHelper
// mechanism expects on stdout (verified against the installed CLI, 2.1.280: it runs the named
// command and parses its stdout as a JSON object of header name to string value — undocumented in
// `--help`, but real, and it re-runs the command on every connection attempt, so a token rotation
// that only rewrites tokenPath's own content needs no re-registration at all). 0700 (owner rwx
// only): this script's own path is what an add-json call names, never a secret itself, but only
// this file's owner should be able to run or read it. Called once per embedded server start
// (bridge/dbmcp.go's own startFn) — idempotent and cheap, so a repeat call (a second enable within
// the same app run) just rewrites the identical content.
func EnsureHeaderHelperScript(home, tokenPath string) (string, error) {
	if err := os.MkdirAll(home, 0o700); err != nil {
		return "", fmt.Errorf("mcpauth: mkdir %s: %w", home, err)
	}
	scriptPath := HeaderHelperScriptPath(home)
	content := "#!/bin/sh\n" +
		"# Kira Studio DB MCP headersHelper — regenerated by the app on every start; do not edit.\n" +
		"tok=$(cat " + mcpinstall.ShellQuote(tokenPath) + ") || exit 1\n" +
		"printf '{\"Authorization\":\"Bearer %s\"}' \"$tok\"\n"
	if err := AtomicWriteFile(scriptPath, []byte(content), 0o700); err != nil {
		return "", fmt.Errorf("mcpauth: write header helper script: %w", err)
	}
	return scriptPath, nil
}
