import type { SourceText } from '../../../shared/domain/ddl';
import { encodePath, type NodePath } from '../../../shared/domain/tree';
import { AdapterError } from '../errors';
import { getRelationInfo, type QueryExecutor } from './catalog';

export type RelationLikeKind = 'table' | 'view' | 'matview';

const RELATION_KEYWORD: Record<RelationLikeKind, string> = {
  table: 'TABLE',
  view: 'VIEW',
  matview: 'MATERIALIZED VIEW',
};

const COMPOSED_SCOPE_NOTE =
  'Composed from catalog metadata: triggers, row-level security policies, grants, ownership, ' +
  'storage parameters, tablespaces and non-default column collations are not included.';

interface RelationShapeRow {
  relkind: string;
  qname: string;
  partition_by: string | null;
  is_partition: boolean;
  viewdef: string | null;
}

interface ColumnDdlRow {
  col: string;
  type: string;
  not_null: boolean;
  identity: string; // '' | 'a' | 'd'
  generated: string; // '' | 's'
  default_expr: string | null;
}

interface ConstraintRow {
  name: string;
  def: string;
}

interface IndexDdlRow {
  def: string;
  name: string;
}

interface SerialSequenceRow {
  col: string;
  seq: string | null;
}

interface CommentStmtRow {
  stmt: string;
}

// pg_get_viewdef/SHOW CREATE emit at most one trailing `;` — remove exactly that, untouched
// otherwise. `statements` carries no trailing semicolons and no blank padding (shared/domain/ddl.ts).
function stripOneTrailingSemicolon(text: string): string {
  const match = /;\s*$/.exec(text);
  return match ? text.slice(0, text.length - match[0].length) : text;
}

function columnLine(col: ColumnDdlRow): string {
  let line = `  ${col.col} ${col.type}`;
  if (col.generated === 's') {
    // generated STORED wins over identity/default — Postgres rejects a column that declares both.
    line += ` GENERATED ALWAYS AS (${col.default_expr}) STORED`;
  } else if (col.identity === 'a') {
    line += ' GENERATED ALWAYS AS IDENTITY';
  } else if (col.identity === 'd') {
    line += ' GENERATED BY DEFAULT AS IDENTITY';
  } else if (col.default_expr !== null) {
    line += ` DEFAULT ${col.default_expr}`;
  }
  if (col.not_null) line += ' NOT NULL';
  return line;
}

/**
 * Composes a `SourceText` from the catalog — there is no `pg_get_tabledef`. Every identifier and
 * literal inside the emitted statements is quoted by the server (`format('%I'/'%L')`,
 * `pg_get_constraintdef`, `pg_get_indexdef`, `pg_get_viewdef`); this file authors no quoting of
 * its own. Queries run sequentially against `exec` — the same single-`Client` rule `describe()`
 * and `getReadTarget()` already document.
 */
export async function buildDdl(
  exec: QueryExecutor,
  segments: NodePath['segments'],
  schema: string,
  object: { kind: RelationLikeKind; name: string },
): Promise<SourceText> {
  const { oid } = await getRelationInfo(exec, schema, object.name);

  const [shape] = await exec<RelationShapeRow>(
    `SELECT c.relkind,
            format('%I.%I', n.nspname, c.relname) AS qname,
            pg_get_partkeydef(c.oid)              AS partition_by,
            c.relispartition                      AS is_partition,
            CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid, true) END AS viewdef
     FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE c.oid = $1::oid`,
    [oid],
  );
  if (!shape) {
    throw new AdapterError('E_NOT_FOUND', `relation "${schema}"."${object.name}" not found`);
  }

  const keyword = RELATION_KEYWORD[object.kind];
  const statements: string[] = [];
  const notes: string[] = [COMPOSED_SCOPE_NOTE];

  if (object.kind === 'table') {
    const columns = await exec<ColumnDdlRow>(
      `SELECT format('%I', a.attname)              AS col,
              format_type(a.atttypid, a.atttypmod) AS type,
              a.attnotnull                          AS not_null,
              a.attidentity                         AS identity,
              a.attgenerated                        AS generated,
              pg_get_expr(d.adbin, d.adrelid)       AS default_expr
       FROM pg_attribute a
       LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
       WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
       ORDER BY a.attnum`,
      [oid],
    );
    // Sequential — not Promise.all: the same single-Client rule describe() documents.
    const constraints = await exec<ConstraintRow>(
      `SELECT format('%I', con.conname) AS name, pg_get_constraintdef(con.oid, true) AS def
       FROM pg_constraint con
       WHERE con.conrelid = $1::oid AND con.contype IN ('p','u','c','f','x')
       ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2
                                 WHEN 'x' THEN 3 ELSE 4 END, con.conname`,
      [oid],
    );
    const indexes = await exec<IndexDdlRow>(
      `SELECT pg_get_indexdef(ix.indexrelid) AS def, i.relname AS name
       FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid
       WHERE ix.indrelid = $1::oid
         AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ix.indexrelid)
       ORDER BY i.relname`,
      [oid],
    );
    // pg_get_serial_sequence resolves the sequence a column's `nextval(...)` default targets by
    // parsing the default expression itself — it returns NULL for identity columns (no default
    // to parse) and for columns with no serial-style default. The referenced sequence must exist
    // before CREATE TABLE runs, since the column's default resolves its `::regclass` cast eagerly.
    const serialSequences = (
      await exec<SerialSequenceRow>(
        `SELECT format('%I', a.attname) AS col, pg_get_serial_sequence($2::text, a.attname) AS seq
         FROM pg_attribute a
         WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
         ORDER BY a.attnum`,
        [oid, shape.qname],
      )
    ).filter((r): r is { col: string; seq: string } => r.seq !== null);

    const partitionBy = shape.partition_by ? ` PARTITION BY ${shape.partition_by}` : '';
    for (const { seq } of serialSequences) {
      statements.push(`CREATE SEQUENCE ${seq}`);
    }
    statements.push(
      `CREATE TABLE ${shape.qname} (\n${columns.map(columnLine).join(',\n')}\n)${partitionBy}`,
    );
    for (const { seq, col } of serialSequences) {
      statements.push(`ALTER SEQUENCE ${seq} OWNED BY ${shape.qname}.${col}`);
    }
    for (const c of constraints) {
      statements.push(`ALTER TABLE ${shape.qname} ADD CONSTRAINT ${c.name} ${c.def}`);
    }
    for (const idx of indexes) statements.push(idx.def);

    if (shape.is_partition) {
      notes.push(
        'This table is a partition of another table; its CREATE TABLE … PARTITION OF form is not reconstructed.',
      );
    }
  } else {
    if (shape.viewdef === null) {
      throw new AdapterError('E_QUERY', `no view definition for "${schema}"."${object.name}"`);
    }
    statements.push(
      `CREATE ${keyword} ${shape.qname} AS\n${stripOneTrailingSemicolon(shape.viewdef)}`,
    );

    if (object.kind === 'matview') {
      const indexes = await exec<IndexDdlRow>(
        `SELECT pg_get_indexdef(ix.indexrelid) AS def, i.relname AS name
         FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid
         WHERE ix.indrelid = $1::oid
           AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ix.indexrelid)
         ORDER BY i.relname`,
        [oid],
      );
      for (const idx of indexes) statements.push(idx.def);
      notes.push(
        'A materialized view is created without data; REFRESH MATERIALIZED VIEW populates it.',
      );
    }
  }

  const [relComment] = await exec<CommentStmtRow>(
    `SELECT format('COMMENT ON %s %s IS %L', $3::text, $2::text, obj_description($1::oid, 'pg_class')) AS stmt
     WHERE obj_description($1::oid, 'pg_class') IS NOT NULL`,
    [oid, shape.qname, keyword],
  );
  if (relComment) statements.push(relComment.stmt);

  const columnComments = await exec<CommentStmtRow>(
    `SELECT format('COMMENT ON COLUMN %s.%I IS %L', $2::text, a.attname,
                  col_description(a.attrelid, a.attnum)) AS stmt
     FROM pg_attribute a
     WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
       AND col_description(a.attrelid, a.attnum) IS NOT NULL
     ORDER BY a.attnum`,
    [oid, shape.qname],
  );
  for (const row of columnComments) statements.push(row.stmt);

  return {
    path: encodePath(segments),
    kind: object.kind,
    qualifiedName: `${schema}.${object.name}`,
    statements,
    origin: 'composed',
    notes,
    generatedAt: new Date().toISOString(),
  };
}
