-- M3: per-connection auto-force-explain on the DB MCP server's run_query path. One plain column
-- with a non-NULL default, the 0004/0020/0021 precedent — first-class rather than an options_json
-- key for the same reason those three give: `options` round-trips through the connection URI and
-- the Copy URI menu item, and a safety gate must not be settable, or clearable, by pasting a URI.
--
-- Deliberately separate from auto_explain (0004), which governs this app's own console and is left
-- untouched: that switch shows a warning strip after the fact, this one can block an AI client on a
-- modal a human must answer. One switch cannot honestly mean both.
--
-- Default 1, not 0: M1 §4.5 recorded run_query's uncapped fetch as the gap M3 exists to close, and
-- a protection nobody turns on protects nobody. Applied to rows exposed under M1/M2 as well, the
-- same not-opt-in tightening 0021 made.
ALTER TABLE connections ADD COLUMN mcp_auto_explain INTEGER NOT NULL DEFAULT 1;
