// The test-owned fixture-key namespace this tier mocks against (Kira Studio's own
// tests/ui/support/ipcChannels.ts, ported and trimmed to this app's own bound surface —
// bridge/index.ts's own `control` object, apps/kira-space/main.go's 13 services). Nothing under
// apps/kira-space/frontend/src imports this: the real wire protocol is the generated Wails
// bindings under apps/kira-space/frontend/bindings/. See mockRuntime.ts's CHANNEL_TO_FQN for the
// other half of this mapping.
export const IPC = {
  githubOpenPullRequestUrl: 'kira:github:openPullRequestUrl',
  linkOpenExternal: 'kira:link:openExternal',

  settingsGetAll: 'kira:settings:getAll',
  settingsSet: 'kira:settings:set',
  settingsChanged: 'kira:settings:changed',

  layoutGetAll: 'kira:layout:getAll',
  layoutSet: 'kira:layout:set',
  layoutChanged: 'kira:layout:changed',

  appFlushBeforeClose: 'kira:app:flush-before-close',
  appFlushed: 'kira:app:flushed',
  windowFlushBeforeClose: 'kira:window:flush-before-close',
  windowFlushed: 'kira:window:flushed',

  filesChooseFolder: 'kira:files:chooseFolder',

  // P116 G1-G7: the menu-pushed commands, keep-awake and new-window bound calls, and the app-metrics
  // push — same values as Kira Studio's own ipcChannels.ts.
  openSettings: 'kira:open-settings',
  toggleProjectPanel: 'kira:menu:toggle-project-panel',
  tabNext: 'kira:menu:tab-next',
  tabPrev: 'kira:menu:tab-prev',
  tabClose: 'kira:menu:tab-close',
  windowsOpenNew: 'kira:windows:openNew',
  // P128 §2.2/§2.6: this app now persists a per-window module mode too, same channels as Kira
  // Studio's own ipcChannels.ts.
  windowsEnsure: 'kira:windows:ensure',
  windowsSetMode: 'kira:windows:set-mode',
  keepAwakeStatus: 'kira:keepAwake:status',
  keepAwakeSetManual: 'kira:keepAwake:setManual',
  keepAwake: 'kira:keepAwake:changed',
  appMetrics: 'kira:app:metrics',
  // P132 Part 2: the operations dock's own toggle, bound calls and push.
  toggleOperationsPanel: 'kira:menu:toggle-operations-panel',
  opsRecent: 'kira:ops:recent',
  opsCancel: 'kira:ops:cancel',
  opUpdate: 'kira:op:update',

  // P119: Kira Studio's own three update channels — same values as its own ipcChannels.ts.
  updateStatus: 'kira:update:status',
  updateInstall: 'kira:update:install',
  updateCancelInstall: 'kira:update:cancelInstall',

  gitClientsList: 'kira:git:clients:list',
  gitClientsRevoke: 'kira:git:clients:revoke',
  gitClientsChanged: 'kira:git:clients',
  gitPairingPending: 'kira:git:pairing:pending',
  gitPairingApprove: 'kira:git:pairing:approve',
  gitPairingDeny: 'kira:git:pairing:deny',
  gitPairing: 'kira:git:pairing',
  gitCredentialPending: 'kira:git:credential:pending',
  gitCredentialProvide: 'kira:git:credential:provide',
  gitCredential: 'kira:git:credential',
  gitVsixStatus: 'kira:git:vsix:status',
  gitVsixInstall: 'kira:git:vsix:install',

  tabsList: 'kira:tabs:list',
  tabsSave: 'kira:tabs:save',

  codeWorkspaceListRepos: 'kira:codeWorkspace:listRepos',
  codeWorkspaceRepoHeads: 'kira:codeWorkspace:repoHeads',
  codeWorkspaceRepoWorktreeLinks: 'kira:codeWorkspace:repoWorktreeLinks',
  codeWorkspaceImportRepo: 'kira:codeWorkspace:importRepo',
  codeWorkspaceRenameRepo: 'kira:codeWorkspace:renameRepo',
  codeWorkspaceRemoveRepo: 'kira:codeWorkspace:removeRepo',
  codeWorkspaceReorderRepos: 'kira:codeWorkspace:reorderRepos',
  codeWorkspaceListFiles: 'kira:codeWorkspace:listFiles',
  codeWorkspaceReadFile: 'kira:codeWorkspace:readFile',
  codeWorkspaceOpenWorkspace: 'kira:codeWorkspace:openWorkspace',
  codeWorkspaceCloseWorkspace: 'kira:codeWorkspace:closeWorkspace',
  codeWorkspaceReadDiff: 'kira:codeWorkspace:readDiff',
  codeWorkspaceStartSearch: 'kira:codeWorkspace:startSearch',
  codeWorkspaceCancelSearch: 'kira:codeWorkspace:cancelSearch',
  codeSearch: 'kira:code:search',

  terminalDefaultCwd: 'kira:terminal:defaultCwd',
  terminalOpen: 'kira:terminal:open',
  terminalWrite: 'kira:terminal:write',
  terminalResize: 'kira:terminal:resize',
  terminalClose: 'kira:terminal:close',
  terminal: 'kira:terminal:data',

  // Boot: the ade module's agent-session hydration, and the agent push channels the workbench shares.
  terminalAgentSessions: 'kira:terminal:agentSessions',
  agentSessions: 'kira:agent:sessions',
  agentEvent: 'kira:agent:event',
  // P145: the ade v2 board surface. `adeTaskBoard` names the bound call; its push counterpart is
  // `adeTaskBoardChanged` (the same call/push split as `gitClientsList`/`gitClientsChanged`).
  adeTaskBoard: 'kira:adetask:board:call',
  adeTaskPrs: 'kira:adetask:prs',
  adeTaskRefresh: 'kira:adetask:refresh',
  adeTaskForcePush: 'kira:adetask:forcePush',
  adeTaskCreateTask: 'kira:adetask:createTask',
  adeTaskCandidateBranches: 'kira:adetask:candidateBranches',
  adeTaskAddExistingBranch: 'kira:adetask:addExistingBranch',
  adeTaskUpdateTask: 'kira:adetask:updateTask',
  adeTaskAddTaskRepo: 'kira:adetask:addTaskRepo',
  adeTaskSetPlan: 'kira:adetask:setPlan',
  adeTaskBacklog: 'kira:adetask:backlog:call',
  adeTaskUpdateBacklogItem: 'kira:adetask:updateBacklogItem',
  adeTaskMoveBacklogItem: 'kira:adetask:moveBacklogItem',
  adeTaskDeleteBacklogItem: 'kira:adetask:deleteBacklogItem',
  adeTaskPromoteBacklogItem: 'kira:adetask:promoteBacklogItem',
  adeTaskAddBacklogItem: 'kira:adetask:addBacklogItem',
  adeTaskWorkflows: 'kira:adetask:workflows:call',
  adeTaskRepos: 'kira:adetask:repos:call',
  adeTaskWorkflowYaml: 'kira:adetask:workflowYaml',
  adeTaskValidateWorkflowYaml: 'kira:adetask:validateWorkflowYaml',
  adeTaskSaveWorkflow: 'kira:adetask:saveWorkflow',
  adeTaskSaveWorkflowYaml: 'kira:adetask:saveWorkflowYaml',
  adeTaskImportWorkflow: 'kira:adetask:importWorkflow',
  adeTaskNewWorkflow: 'kira:adetask:newWorkflow',
  adeTaskUpdateRepo: 'kira:adetask:updateRepo',
  adeTaskAddFolder: 'kira:adetask:addFolder',
  adeTaskSetFolderWatch: 'kira:adetask:setFolderWatch',
  adeTaskRemoveFolder: 'kira:adetask:removeFolder',
  adeTaskStartRun: 'kira:adetask:startRun',
  adeTaskSetTaskWorkflow: 'kira:adetask:setTaskWorkflow',
  adeTaskApprove: 'kira:adetask:approve',
  adeTaskRetryRun: 'kira:adetask:retryRun',
  adeTaskStageDone: 'kira:adetask:stageDone',
  adeTaskSetTaskStage: 'kira:adetask:setTaskStage',
  adeTaskRetrySetup: 'kira:adetask:retrySetup',
  adeTaskReadLog: 'kira:adetask:readLog',
  adeTaskSessions: 'kira:adetask:sessions:call',
  adeTaskStopRun: 'kira:adetask:stopRun',
  adeTaskTakeOver: 'kira:adetask:takeOver',
  adeTaskLaunchStage: 'kira:adetask:launchStage',
  adeTaskStartBranch: 'kira:adetask:startBranch',
  adeTaskSend: 'kira:adetask:send',
  adeTaskFocusSession: 'kira:adetask:focusSession',
  adeTaskReviewAgent: 'kira:adetask:reviewAgent',
  adeTaskLaunchReviewAgent: 'kira:adetask:launchReviewAgent',
  adeTaskOpenReviewWindow: 'kira:adetask:openReviewWindow',
  adeTaskReviewWindowTarget: 'kira:adetask:reviewWindowTarget',
  adeTaskGitHubSyncPlan: 'kira:adetask:gitHubSyncPlan',
  adeTaskGitHubSyncApply: 'kira:adetask:gitHubSyncApply',
  adeTaskArchiveRisk: 'kira:adetask:archiveRisk',
  adeTaskArchiveTask: 'kira:adetask:archiveTask',
  adeTaskRecordMerge: 'kira:adetask:recordMerge',
  adeTaskSetQueuedAfter: 'kira:adetask:setQueuedAfter',
  adeTaskBoardChanged: 'kira:adetask:board',
  adeTaskBacklogChanged: 'kira:adetask:backlog',
  adeTaskReposChanged: 'kira:adetask:repos',
  adeTaskWorkflowsChanged: 'kira:adetask:workflows',
  adeTaskRunsChanged: 'kira:adetask:runs',
  adeTaskLogChanged: 'kira:adetask:log',
  adeTaskSessionsChanged: 'kira:adetask:sessions',
  adeTaskOpenSession: 'kira:adetask:open-session',
} as const;
