// Generated by tests/ipc/rabbitmq/rabbitmq.backend.spec.ts with
// KIRA_IPC_FIXTURES=write — do not hand-edit (P50 D5). The backend spec asserts every run's
// real response against this file; the frontend spec mocks the IPC layer with the exact same
// file. That is the split's anti-drift rule: a frontend spec cannot mock a shape the backend
// has stopped producing without this file's own backend assertion failing first.
import type { ControlSnapshot, PortSnapshot } from '../support/types';

export const controlSnapshots: ControlSnapshot[] = [
  {
    channel: 'kira:connections:list',
    response: [
      {
        id: 'test-rabbitmq',
        sortOrder: 0,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z',
        name: 'Test RabbitMQ',
        kind: 'rabbitmq',
        color: 'indigo',
        mode: 'fields',
        readOnly: false,
        host: 'fixture-host',
        port: 0,
        database: 'kira',
        username: 'guest',
        uri: null,
        options: {},
        preconnect: null,
        preconnectSidecar: false,
      },
    ],
  },
  {
    channel: 'kira:connections:states',
    response: [],
  },
  {
    channel: 'kira:connections:connect',
    args: {
      id: 'test-rabbitmq',
    },
    response: {
      connectionId: 'test-rabbitmq',
      status: 'connected',
      serverVersion: 'RabbitMQ 4.3.5',
      error: null,
      since: 0,
      caps: {
        tabular: false,
        documents: false,
        keyValue: false,
        stream: true,
        keyBrowser: false,
        defaultPageKind: 'stream',
        sql: false,
        definition: true,
        describe: false,
        projection: false,
        serverFilter: false,
        exactCount: false,
        pagination: 'batch',
        foreignKeys: false,
        canInsert: true,
        canUpdate: false,
        canDelete: false,
        writable: true,
        transactions: false,
        cancel: true,
        fileTransfer: false,
        maxPageSize: 500,
      },
    },
  },
  {
    channel: 'kira:tree:children',
    args: {
      connectionId: 'test-rabbitmq',
      path: '',
      refresh: false,
    },
    response: {
      nodes: [
        {
          kind: 'database',
          name: 'kira',
          path: 'database:kira',
          hasChildren: true,
        },
      ],
      source: 'server',
      truncated: false,
    },
  },
  {
    channel: 'kira:tree:children',
    args: {
      connectionId: 'test-rabbitmq',
      path: 'database:kira',
      refresh: false,
    },
    response: {
      nodes: [
        {
          kind: 'queue',
          name: 'big-queue',
          path: 'database:kira/queue:big-queue',
          hasChildren: false,
          detail: '2K messages · classic',
        },
        {
          kind: 'queue',
          name: 'binary-queue',
          path: 'database:kira/queue:binary-queue',
          hasChildren: false,
          detail: '2 messages · classic',
        },
        {
          kind: 'queue',
          name: 'dlx-queue',
          path: 'database:kira/queue:dlx-queue',
          hasChildren: false,
          detail: '0 messages · classic',
        },
        {
          kind: 'queue',
          name: 'empty-queue',
          path: 'database:kira/queue:empty-queue',
          hasChildren: false,
          detail: '0 messages · classic',
        },
        {
          kind: 'queue',
          name: 'orders',
          path: 'database:kira/queue:orders',
          hasChildren: false,
          detail: '6 messages · classic',
        },
        {
          kind: 'queue',
          name: 'quorum-queue',
          path: 'database:kira/queue:quorum-queue',
          hasChildren: false,
          detail: '0 messages · quorum',
        },
        {
          kind: 'queue',
          name: 'stream-queue',
          path: 'database:kira/queue:stream-queue',
          hasChildren: false,
          detail: '~ messages · stream',
        },
        {
          kind: 'queue',
          name: 'weird/name ✓',
          path: 'database:kira/queue:weird%2Fname%20%E2%9C%93',
          hasChildren: false,
          detail: '1 messages · classic',
        },
        {
          kind: 'exchange',
          name: 'alt.exchange',
          path: 'database:kira/exchange:alt.exchange',
          hasChildren: false,
          detail: 'fanout',
        },
        {
          kind: 'exchange',
          name: 'amq.direct',
          path: 'database:kira/exchange:amq.direct',
          hasChildren: false,
          detail: 'direct',
        },
        {
          kind: 'exchange',
          name: 'amq.fanout',
          path: 'database:kira/exchange:amq.fanout',
          hasChildren: false,
          detail: 'fanout',
        },
        {
          kind: 'exchange',
          name: 'amq.headers',
          path: 'database:kira/exchange:amq.headers',
          hasChildren: false,
          detail: 'headers',
        },
        {
          kind: 'exchange',
          name: 'amq.match',
          path: 'database:kira/exchange:amq.match',
          hasChildren: false,
          detail: 'headers',
        },
        {
          kind: 'exchange',
          name: 'amq.rabbitmq.trace',
          path: 'database:kira/exchange:amq.rabbitmq.trace',
          hasChildren: false,
          detail: 'topic',
        },
        {
          kind: 'exchange',
          name: 'amq.topic',
          path: 'database:kira/exchange:amq.topic',
          hasChildren: false,
          detail: 'topic',
        },
        {
          kind: 'exchange',
          name: 'events.fanout',
          path: 'database:kira/exchange:events.fanout',
          hasChildren: false,
          detail: 'fanout',
        },
        {
          kind: 'exchange',
          name: 'events.topic',
          path: 'database:kira/exchange:events.topic',
          hasChildren: false,
          detail: 'topic',
        },
        {
          kind: 'exchange',
          name: 'orders.direct',
          path: 'database:kira/exchange:orders.direct',
          hasChildren: false,
          detail: 'direct',
        },
        {
          kind: 'exchange',
          name: 'props.headers',
          path: 'database:kira/exchange:props.headers',
          hasChildren: false,
          detail: 'headers',
        },
      ],
      source: 'server',
      truncated: false,
    },
  },
  {
    channel: 'kira:tree:definition',
    args: {
      connectionId: 'test-rabbitmq',
      path: 'database:kira/exchange:orders.direct',
      refresh: false,
      tabId: null,
    },
    response: {
      definition: {
        path: 'database:kira/exchange:orders.direct',
        kind: 'exchange',
        qualifiedName: 'orders.direct',
        language: 'json',
        statements: [
          '{\n  "arguments": {},\n  "auto_delete": false,\n  "durable": true,\n  "incoming": [],\n  "internal": false,\n  "message_stats": {\n    "publish_in": 6,\n    "publish_in_details": {\n      "rate": 0\n    },\n    "publish_out": 6,\n    "publish_out_details": {\n      "rate": 0\n    }\n  },\n  "name": "orders.direct",\n  "outgoing": [],\n  "type": "direct",\n  "user_who_performed_action": "guest",\n  "vhost": "kira"\n}',
        ],
        origin: 'server',
        notes: [
          "A binding has no name of its own — the key shown here is one the management API synthesises from the binding's own properties.",
        ],
        constraints: [],
        documentSchema: null,
        sections: [
          {
            title: 'Exchange',
            rows: [
              {
                name: 'Type',
                value: 'direct',
                detail: null,
              },
              {
                name: 'Durable',
                value: 'true',
                detail: null,
              },
              {
                name: 'Auto-delete',
                value: 'false',
                detail: null,
              },
              {
                name: 'Internal',
                value: 'false',
                detail: null,
              },
              {
                name: 'Policy',
                value: '(none)',
                detail: null,
              },
            ],
          },
          {
            title: 'Arguments',
            rows: [
              {
                name: '(none set)',
                value: '',
                detail: null,
              },
            ],
          },
          {
            title: 'Bindings from this exchange',
            rows: [
              {
                name: 'orders',
                value: 'orders',
                detail: null,
              },
            ],
          },
          {
            title: 'Bindings to this exchange',
            rows: [],
          },
        ],
        generatedAt: '2024-01-01T00:00:00.000Z',
      },
      source: 'server',
    },
  },
];

export const portSnapshots: PortSnapshot[] = [
  {
    op: 'data:read',
    payload: {
      opId: 'be-poll-orders',
      tabId: null,
      connectionId: 'test-rabbitmq',
      path: 'database:kira/queue:orders',
      projection: null,
      filter: null,
      sort: null,
      pageSize: 100,
      cursor: {
        mode: 'offset',
        offset: 0,
      },
    },
    response: {
      kind: 'read',
      page: {
        kind: 'stream',
        keys: ['orders', 'orders', 'orders', 'orders', 'orders', 'orders'],
        headers: [
          '{"seq":0,"source":"seed"}',
          '{"seq":1,"source":"seed"}',
          '{"seq":2,"source":"seed"}',
          '{"seq":3,"source":"seed"}',
          '{"seq":4,"source":"seed"}',
          '{"seq":5,"source":"seed"}',
        ],
        attrs: [
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":5,"correlation_id":"order-0"}',
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":4,"correlation_id":"order-1"}',
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":3,"correlation_id":"order-2"}',
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":2,"correlation_id":"order-3"}',
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":1,"correlation_id":"order-4"}',
          '{"exchange":"orders.direct","redelivered":false,"payload_bytes":9,"payload_encoding":"string","message_count":0,"correlation_id":"order-5"}',
        ],
        timestamps: [
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
        ],
        bodies: ['{"seq":0}', '{"seq":1}', '{"seq":2}', '{"seq":3}', '{"seq":4}', '{"seq":5}'],
        position: {
          offset: null,
          pageSize: 100,
          hasMore: false,
          nextToken: null,
          prevToken: null,
          strategy: 'batch',
        },
        visibilityTimeoutSeconds: null,
      },
      source: 'server',
    },
  },
  {
    op: 'data:mutate',
    payload: {
      opId: 'be-publish-orders',
      tabId: null,
      connectionId: 'test-rabbitmq',
      path: 'database:kira/queue:orders',
      ops: [
        {
          kind: 'insert',
          values: {
            $body: 'hello from the UI',
          },
        },
      ],
    },
    response: {
      kind: 'mutate',
      affectedRows: 1,
    },
  },
  {
    op: 'data:invalidate',
    payload: {
      connectionId: 'test-rabbitmq',
      path: 'database:kira/queue:orders',
    },
    response: {
      kind: 'invalidate',
    },
  },
  {
    op: 'data:read',
    payload: {
      opId: 'be-poll-orders',
      tabId: null,
      connectionId: 'test-rabbitmq',
      path: 'database:kira/queue:orders',
      projection: null,
      filter: null,
      sort: null,
      pageSize: 100,
      cursor: {
        mode: 'offset',
        offset: 0,
      },
    },
    response: {
      kind: 'read',
      page: {
        kind: 'stream',
        keys: ['orders', 'orders', 'orders', 'orders', 'orders', 'orders', 'orders'],
        headers: [
          '{"seq":0,"source":"seed"}',
          '{"seq":1,"source":"seed"}',
          '{"seq":2,"source":"seed"}',
          '{"seq":3,"source":"seed"}',
          '{"seq":4,"source":"seed"}',
          '{"seq":5,"source":"seed"}',
          '{}',
        ],
        attrs: [
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":6,"correlation_id":"order-0"}',
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":5,"correlation_id":"order-1"}',
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":4,"correlation_id":"order-2"}',
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":3,"correlation_id":"order-3"}',
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":2,"correlation_id":"order-4"}',
          '{"exchange":"orders.direct","redelivered":true,"payload_bytes":9,"payload_encoding":"string","message_count":1,"correlation_id":"order-5"}',
          '{"exchange":"","redelivered":false,"payload_bytes":17,"payload_encoding":"string","message_count":0}',
        ],
        timestamps: [
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z',
        ],
        bodies: [
          '{"seq":0}',
          '{"seq":1}',
          '{"seq":2}',
          '{"seq":3}',
          '{"seq":4}',
          '{"seq":5}',
          'hello from the UI',
        ],
        position: {
          offset: null,
          pageSize: 100,
          hasMore: false,
          nextToken: null,
          prevToken: null,
          strategy: 'batch',
        },
        visibilityTimeoutSeconds: null,
      },
      source: 'server',
    },
  },
];
