package postgres

import (
	"context"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/kirathecat/kira-studio/apps/kira-studio/internal/adapters"
	"github.com/kirathecat/kira-studio/apps/kira-studio/internal/storage/model"
)

// relationKeyword is definition.ts's RELATION_KEYWORD.
var relationKeyword = map[string]string{
	"table": "TABLE", "view": "VIEW", "matview": "MATERIALIZED VIEW",
}

const composedScopeNote = "Composed from catalog metadata: triggers, row-level security policies, " +
	"grants, ownership, storage parameters, tablespaces and non-default column collations are not included."

var constraintType = map[string]string{
	"p": "primaryKey", "u": "unique", "c": "check", "f": "foreignKey", "x": "exclusion",
}

type columnDDLRow struct {
	col, colType        string
	notNull             bool
	identity, generated string
	defaultExpr         *string
}

func columnLine(col columnDDLRow) string {
	line := "  " + col.col + " " + col.colType
	switch {
	case col.generated == "s":
		// generated STORED wins over identity/default — Postgres rejects a column that declares both.
		line += " GENERATED ALWAYS AS (" + derefOr(col.defaultExpr, "") + ") STORED"
	case col.identity == "a":
		line += " GENERATED ALWAYS AS IDENTITY"
	case col.identity == "d":
		line += " GENERATED BY DEFAULT AS IDENTITY"
	case col.defaultExpr != nil:
		line += " DEFAULT " + *col.defaultExpr
	}
	if col.notNull {
		line += " NOT NULL"
	}
	return line
}

func derefOr(s *string, fallback string) string {
	if s == nil {
		return fallback
	}
	return *s
}

// buildDefinition is definition.ts's buildDefinition: composes a SourceText from the catalog —
// there is no pg_get_tabledef. Every identifier and literal inside the emitted statements is
// quoted by the server (format('%I'/'%L'), pg_get_constraintdef, pg_get_indexdef, pg_get_viewdef);
// this file authors no quoting of its own. Queries run sequentially against exec — the same
// single-connection rule describe() and getReadTarget() already document.
func buildDefinition(ctx context.Context, exec queryExec, segments []model.PathSegment, schema string, objectKind, objectName string) (model.ObjectDefinition, error) {
	info, err := getRelationInfo(ctx, exec, schema, objectName)
	if err != nil {
		return model.ObjectDefinition{}, err
	}

	var relkind, qname string
	var partitionBy *string
	var isPartition bool
	var viewdef *string
	found := false
	err = exec(ctx, `SELECT c.relkind,
	        format('%I.%I', n.nspname, c.relname) AS qname,
	        pg_get_partkeydef(c.oid)              AS partition_by,
	        c.relispartition                      AS is_partition,
	        CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid, true) END AS viewdef
	 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
	 WHERE c.oid = $1::oid`, []any{info.OID}, func(rows pgx.Rows) error {
		found = true
		return rows.Scan(&relkind, &qname, &partitionBy, &isPartition, &viewdef)
	})
	if err != nil {
		return model.ObjectDefinition{}, err
	}
	if !found {
		return model.ObjectDefinition{}, adapters.New(adapters.CodeNotFound, "relation \""+schema+"\".\""+objectName+"\" not found", nil)
	}

	keyword := relationKeyword[objectKind]
	var statements []string
	notes := []string{composedScopeNote}
	var constraintMetas []model.ConstraintMeta

	if objectKind == "table" {
		var columns []columnDDLRow
		err = exec(ctx, `SELECT format('%I', a.attname)              AS col,
	              format_type(a.atttypid, a.atttypmod) AS type,
	              a.attnotnull                          AS not_null,
	              a.attidentity                         AS identity,
	              a.attgenerated                        AS generated,
	              pg_get_expr(d.adbin, d.adrelid)       AS default_expr
	       FROM pg_attribute a
	       LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
	       WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	       ORDER BY a.attnum`, []any{info.OID}, func(rows pgx.Rows) error {
			var c columnDDLRow
			if err := rows.Scan(&c.col, &c.colType, &c.notNull, &c.identity, &c.generated, &c.defaultExpr); err != nil {
				return err
			}
			columns = append(columns, c)
			return nil
		})
		if err != nil {
			return model.ObjectDefinition{}, err
		}

		type constraintRow struct {
			name, def, contype string
		}
		var constraints []constraintRow
		err = exec(ctx, `SELECT format('%I', con.conname) AS name, pg_get_constraintdef(con.oid, true) AS def,
	              con.contype::text AS contype
	       FROM pg_constraint con
	       WHERE con.conrelid = $1::oid AND con.contype IN ('p','u','c','f','x')
	       ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2
	                                 WHEN 'x' THEN 3 ELSE 4 END, con.conname`,
			[]any{info.OID}, func(rows pgx.Rows) error {
				var c constraintRow
				if err := rows.Scan(&c.name, &c.def, &c.contype); err != nil {
					return err
				}
				constraints = append(constraints, c)
				return nil
			})
		if err != nil {
			return model.ObjectDefinition{}, err
		}
		// Reuses the same pg_constraint rows the DDL statements below compose from (D11) — zero
		// extra round trips. The engine's own constraintdef text is rendered verbatim (D11).
		constraintMetas = make([]model.ConstraintMeta, len(constraints))
		for i, c := range constraints {
			typ, ok := constraintType[c.contype]
			if !ok {
				typ = "check"
			}
			constraintMetas[i] = model.ConstraintMeta{Name: c.name, Type: typ, Definition: c.def}
		}

		type indexDDLRow struct{ def, name string }
		var indexes []indexDDLRow
		err = exec(ctx, `SELECT pg_get_indexdef(ix.indexrelid) AS def, i.relname AS name
	       FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid
	       WHERE ix.indrelid = $1::oid
	         AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ix.indexrelid)
	       ORDER BY i.relname`, []any{info.OID}, func(rows pgx.Rows) error {
			var r indexDDLRow
			if err := rows.Scan(&r.def, &r.name); err != nil {
				return err
			}
			indexes = append(indexes, r)
			return nil
		})
		if err != nil {
			return model.ObjectDefinition{}, err
		}

		// pg_get_serial_sequence resolves the sequence a column's nextval(...) default targets by
		// parsing the default expression itself — it returns NULL for identity columns (no
		// default to parse) and for columns with no serial-style default. The referenced sequence
		// must exist before CREATE TABLE runs, since the column's default resolves its ::regclass
		// cast eagerly.
		type serialSeqRow struct{ col, seq string }
		var serialSequences []serialSeqRow
		err = exec(ctx, `SELECT format('%I', a.attname) AS col, pg_get_serial_sequence($2::text, a.attname) AS seq
	         FROM pg_attribute a
	         WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	         ORDER BY a.attnum`, []any{info.OID, qname}, func(rows pgx.Rows) error {
			var col string
			var seq *string
			if err := rows.Scan(&col, &seq); err != nil {
				return err
			}
			if seq != nil {
				serialSequences = append(serialSequences, serialSeqRow{col: col, seq: *seq})
			}
			return nil
		})
		if err != nil {
			return model.ObjectDefinition{}, err
		}

		partitionSQL := ""
		if partitionBy != nil && *partitionBy != "" {
			partitionSQL = " PARTITION BY " + *partitionBy
		}
		for _, s := range serialSequences {
			statements = append(statements, "CREATE SEQUENCE "+s.seq)
		}
		colLines := make([]string, len(columns))
		for i, c := range columns {
			colLines[i] = columnLine(c)
		}
		statements = append(statements, "CREATE TABLE "+qname+" (\n"+strings.Join(colLines, ",\n")+"\n)"+partitionSQL)
		for _, s := range serialSequences {
			statements = append(statements, "ALTER SEQUENCE "+s.seq+" OWNED BY "+qname+"."+s.col)
		}
		for _, c := range constraints {
			statements = append(statements, "ALTER TABLE "+qname+" ADD CONSTRAINT "+c.name+" "+c.def)
		}
		for _, idx := range indexes {
			statements = append(statements, idx.def)
		}

		if isPartition {
			notes = append(notes, "This table is a partition of another table; its CREATE TABLE … PARTITION OF form is not reconstructed.")
		}
	} else {
		if viewdef == nil {
			return model.ObjectDefinition{}, adapters.New(adapters.CodeQuery, "no view definition for \""+schema+"\".\""+objectName+"\"", nil)
		}
		statements = append(statements, "CREATE "+keyword+" "+qname+" AS\n"+adapters.StripOneTrailingSemicolon(*viewdef))

		if objectKind == "matview" {
			type indexDDLRow struct{ def, name string }
			var indexes []indexDDLRow
			err = exec(ctx, `SELECT pg_get_indexdef(ix.indexrelid) AS def, i.relname AS name
	         FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid
	         WHERE ix.indrelid = $1::oid
	           AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ix.indexrelid)
	         ORDER BY i.relname`, []any{info.OID}, func(rows pgx.Rows) error {
				var r indexDDLRow
				if err := rows.Scan(&r.def, &r.name); err != nil {
					return err
				}
				indexes = append(indexes, r)
				return nil
			})
			if err != nil {
				return model.ObjectDefinition{}, err
			}
			for _, idx := range indexes {
				statements = append(statements, idx.def)
			}
			notes = append(notes, "A materialized view is created without data; REFRESH MATERIALIZED VIEW populates it.")
		}
	}

	var relComment *string
	err = exec(ctx, `SELECT format('COMMENT ON %s %s IS %L', $3::text, $2::text, obj_description($1::oid, 'pg_class')) AS stmt
	 WHERE obj_description($1::oid, 'pg_class') IS NOT NULL`,
		[]any{info.OID, qname, keyword}, func(rows pgx.Rows) error {
			var stmt string
			if err := rows.Scan(&stmt); err != nil {
				return err
			}
			relComment = &stmt
			return nil
		})
	if err != nil {
		return model.ObjectDefinition{}, err
	}
	if relComment != nil {
		statements = append(statements, *relComment)
	}

	err = exec(ctx, `SELECT format('COMMENT ON COLUMN %s.%I IS %L', $2::text, a.attname,
	              col_description(a.attrelid, a.attnum)) AS stmt
	 FROM pg_attribute a
	 WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	   AND col_description(a.attrelid, a.attnum) IS NOT NULL
	 ORDER BY a.attnum`, []any{info.OID, qname}, func(rows pgx.Rows) error {
		var stmt string
		if err := rows.Scan(&stmt); err != nil {
			return err
		}
		statements = append(statements, stmt)
		return nil
	})
	if err != nil {
		return model.ObjectDefinition{}, err
	}

	return model.ObjectDefinition{
		Path: model.EncodePath(segments), Kind: objectKind, QualifiedName: schema + "." + objectName,
		Statements: statements, Language: "sql", Origin: "composed", Notes: notes,
		Constraints: constraintMetas, DocumentSchema: nil, Sections: []model.DefinitionSection{},
		GeneratedAt: time.Now().UTC().Format(time.RFC3339Nano),
	}, nil
}
