package postgres

import (
	"context"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/kirathecat/kira-studio/apps/kira-studio/internal/adapters"
	"github.com/kirathecat/kira-studio/apps/kira-studio/internal/storage/model"
)

// relationKeyword is definition.ts's RELATION_KEYWORD.
var relationKeyword = map[string]string{
	"table": "TABLE", "view": "VIEW", "matview": "MATERIALIZED VIEW",
}

const composedScopeNote = "Composed from catalog metadata: triggers, row-level security policies, " +
	"grants, ownership, storage parameters, tablespaces and non-default column collations are not included."

var constraintType = map[string]string{
	"p": "primaryKey", "u": "unique", "c": "check", "f": "foreignKey", "x": "exclusion",
}

type columnDDLRow struct {
	col, colType        string
	notNull             bool
	identity, generated string
	defaultExpr         *string
}

func columnLine(col columnDDLRow) string {
	line := "  " + col.col + " " + col.colType
	switch {
	case col.generated == "s":
		// generated STORED wins over identity/default — Postgres rejects a column that declares both.
		line += " GENERATED ALWAYS AS (" + derefOr(col.defaultExpr, "") + ") STORED"
	case col.identity == "a":
		line += " GENERATED ALWAYS AS IDENTITY"
	case col.identity == "d":
		line += " GENERATED BY DEFAULT AS IDENTITY"
	case col.defaultExpr != nil:
		line += " DEFAULT " + *col.defaultExpr
	}
	if col.notNull {
		line += " NOT NULL"
	}
	return line
}

func derefOr(s *string, fallback string) string {
	if s == nil {
		return fallback
	}
	return *s
}

// relationMeta is fetchRelationMeta's result: the relation-level metadata every objectKind needs.
type relationMeta struct {
	relkind     string
	qname       string
	partitionBy *string
	isPartition bool
	viewdef     *string
}

// fetchRelationMeta is buildDefinition's first query: the relation's kind, qualified name,
// partition key and (for a view/matview) its definition.
func fetchRelationMeta(ctx context.Context, exec queryExec, schema, objectName string, oid string) (relationMeta, error) {
	var m relationMeta
	found := false
	err := exec(ctx, `SELECT c.relkind,
	        format('%I.%I', n.nspname, c.relname) AS qname,
	        pg_get_partkeydef(c.oid)              AS partition_by,
	        c.relispartition                      AS is_partition,
	        CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid, true) END AS viewdef
	 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
	 WHERE c.oid = $1::oid`, []any{oid}, func(rows pgx.Rows) error {
		found = true
		return rows.Scan(&m.relkind, &m.qname, &m.partitionBy, &m.isPartition, &m.viewdef)
	})
	if err != nil {
		return relationMeta{}, err
	}
	if !found {
		return relationMeta{}, adapters.New(adapters.CodeNotFound, "relation \""+schema+"\".\""+objectName+"\" not found", nil)
	}
	return m, nil
}

// fetchColumns is buildDefinition's column-DDL query.
func fetchColumns(ctx context.Context, exec queryExec, oid string) ([]columnDDLRow, error) {
	var columns []columnDDLRow
	err := exec(ctx, `SELECT format('%I', a.attname)              AS col,
	              format_type(a.atttypid, a.atttypmod) AS type,
	              a.attnotnull                          AS not_null,
	              a.attidentity                         AS identity,
	              a.attgenerated                        AS generated,
	              pg_get_expr(d.adbin, d.adrelid)       AS default_expr
	       FROM pg_attribute a
	       LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
	       WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	       ORDER BY a.attnum`, []any{oid}, func(rows pgx.Rows) error {
		var c columnDDLRow
		if err := rows.Scan(&c.col, &c.colType, &c.notNull, &c.identity, &c.generated, &c.defaultExpr); err != nil {
			return err
		}
		columns = append(columns, c)
		return nil
	})
	return columns, err
}

type constraintRow struct {
	name, def, contype string
}

// fetchConstraints is buildDefinition's constraint query, also the source for constraintMetas
// (D11: same rows, zero extra round trips).
func fetchConstraints(ctx context.Context, exec queryExec, oid string) ([]constraintRow, error) {
	var constraints []constraintRow
	err := exec(ctx, `SELECT format('%I', con.conname) AS name, pg_get_constraintdef(con.oid, true) AS def,
	              con.contype::text AS contype
	       FROM pg_constraint con
	       WHERE con.conrelid = $1::oid AND con.contype IN ('p','u','c','f','x')
	       ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2
	                                 WHEN 'x' THEN 3 ELSE 4 END, con.conname`,
		[]any{oid}, func(rows pgx.Rows) error {
			var c constraintRow
			if err := rows.Scan(&c.name, &c.def, &c.contype); err != nil {
				return err
			}
			constraints = append(constraints, c)
			return nil
		})
	return constraints, err
}

func constraintMetasOf(constraints []constraintRow) []model.ConstraintMeta {
	metas := make([]model.ConstraintMeta, len(constraints))
	for i, c := range constraints {
		typ, ok := constraintType[c.contype]
		if !ok {
			typ = "check"
		}
		metas[i] = model.ConstraintMeta{Name: c.name, Type: typ, Definition: c.def}
	}
	return metas
}

type indexDDLRow struct{ def, name string }

// fetchIndexes is buildDefinition's non-constraint-backed index query, shared by the table and
// matview branches.
func fetchIndexes(ctx context.Context, exec queryExec, oid string) ([]indexDDLRow, error) {
	var indexes []indexDDLRow
	err := exec(ctx, `SELECT pg_get_indexdef(ix.indexrelid) AS def, i.relname AS name
	       FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid
	       WHERE ix.indrelid = $1::oid
	         AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ix.indexrelid)
	       ORDER BY i.relname`, []any{oid}, func(rows pgx.Rows) error {
		var r indexDDLRow
		if err := rows.Scan(&r.def, &r.name); err != nil {
			return err
		}
		indexes = append(indexes, r)
		return nil
	})
	return indexes, err
}

type serialSeqRow struct{ col, seq string }

// fetchSerialSequences resolves each column's nextval(...) sequence via pg_get_serial_sequence —
// NULL for an identity column (no default to parse) or one with no serial-style default. The
// referenced sequence must exist before CREATE TABLE runs, since the column's default resolves its
// ::regclass cast eagerly.
func fetchSerialSequences(ctx context.Context, exec queryExec, oid string, qname string) ([]serialSeqRow, error) {
	var serialSequences []serialSeqRow
	err := exec(ctx, `SELECT format('%I', a.attname) AS col, pg_get_serial_sequence($2::text, a.attname) AS seq
	         FROM pg_attribute a
	         WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	         ORDER BY a.attnum`, []any{oid, qname}, func(rows pgx.Rows) error {
		var col string
		var seq *string
		if err := rows.Scan(&col, &seq); err != nil {
			return err
		}
		if seq != nil {
			serialSequences = append(serialSequences, serialSeqRow{col: col, seq: *seq})
		}
		return nil
	})
	return serialSequences, err
}

// buildTableStatements composes the CREATE SEQUENCE/TABLE/ALTER statements for objectKind ==
// "table" and returns them alongside the constraint metas and a note when the table is itself a
// partition. Statement append order drives the emitted DDL text (D11) and must stay exactly as-is.
func buildTableStatements(ctx context.Context, exec queryExec, oid string, qname string, m relationMeta) ([]string, []model.ConstraintMeta, []string, error) {
	columns, err := fetchColumns(ctx, exec, oid)
	if err != nil {
		return nil, nil, nil, err
	}
	constraints, err := fetchConstraints(ctx, exec, oid)
	if err != nil {
		return nil, nil, nil, err
	}
	indexes, err := fetchIndexes(ctx, exec, oid)
	if err != nil {
		return nil, nil, nil, err
	}
	serialSequences, err := fetchSerialSequences(ctx, exec, oid, qname)
	if err != nil {
		return nil, nil, nil, err
	}

	partitionSQL := ""
	if m.partitionBy != nil && *m.partitionBy != "" {
		partitionSQL = " PARTITION BY " + *m.partitionBy
	}

	var statements []string
	for _, s := range serialSequences {
		statements = append(statements, "CREATE SEQUENCE "+s.seq)
	}
	colLines := make([]string, len(columns))
	for i, c := range columns {
		colLines[i] = columnLine(c)
	}
	statements = append(statements, "CREATE TABLE "+qname+" (\n"+strings.Join(colLines, ",\n")+"\n)"+partitionSQL)
	for _, s := range serialSequences {
		statements = append(statements, "ALTER SEQUENCE "+s.seq+" OWNED BY "+qname+"."+s.col)
	}
	for _, c := range constraints {
		statements = append(statements, "ALTER TABLE "+qname+" ADD CONSTRAINT "+c.name+" "+c.def)
	}
	for _, idx := range indexes {
		statements = append(statements, idx.def)
	}

	var notes []string
	if m.isPartition {
		notes = append(notes, "This table is a partition of another table; its CREATE TABLE … PARTITION OF form is not reconstructed.")
	}
	return statements, constraintMetasOf(constraints), notes, nil
}

// buildViewStatements composes the CREATE VIEW/MATERIALIZED VIEW statement, plus a matview's own
// non-constraint-backed indexes.
func buildViewStatements(ctx context.Context, exec queryExec, oid string, qname, schema, objectKind, objectName string, keyword string, m relationMeta) ([]string, []string, error) {
	if m.viewdef == nil {
		return nil, nil, adapters.New(adapters.CodeQuery, "no view definition for \""+schema+"\".\""+objectName+"\"", nil)
	}
	statements := []string{"CREATE " + keyword + " " + qname + " AS\n" + adapters.StripOneTrailingSemicolon(*m.viewdef)}

	var notes []string
	if objectKind == "matview" {
		indexes, err := fetchIndexes(ctx, exec, oid)
		if err != nil {
			return nil, nil, err
		}
		for _, idx := range indexes {
			statements = append(statements, idx.def)
		}
		notes = append(notes, "A materialized view is created without data; REFRESH MATERIALIZED VIEW populates it.")
	}
	return statements, notes, nil
}

// fetchComments is buildDefinition's two comment queries: the relation's own COMMENT ON statement
// (at most one) and each commented column's.
func fetchComments(ctx context.Context, exec queryExec, oid string, qname, keyword string) (relComment *string, columnComments []string, err error) {
	err = exec(ctx, `SELECT format('COMMENT ON %s %s IS %L', $3::text, $2::text, obj_description($1::oid, 'pg_class')) AS stmt
	 WHERE obj_description($1::oid, 'pg_class') IS NOT NULL`,
		[]any{oid, qname, keyword}, func(rows pgx.Rows) error {
			var stmt string
			if err := rows.Scan(&stmt); err != nil {
				return err
			}
			relComment = &stmt
			return nil
		})
	if err != nil {
		return nil, nil, err
	}

	err = exec(ctx, `SELECT format('COMMENT ON COLUMN %s.%I IS %L', $2::text, a.attname,
	              col_description(a.attrelid, a.attnum)) AS stmt
	 FROM pg_attribute a
	 WHERE a.attrelid = $1::oid AND a.attnum > 0 AND NOT a.attisdropped
	   AND col_description(a.attrelid, a.attnum) IS NOT NULL
	 ORDER BY a.attnum`, []any{oid, qname}, func(rows pgx.Rows) error {
		var stmt string
		if err := rows.Scan(&stmt); err != nil {
			return err
		}
		columnComments = append(columnComments, stmt)
		return nil
	})
	if err != nil {
		return nil, nil, err
	}
	return relComment, columnComments, nil
}

// buildDefinition is definition.ts's buildDefinition: composes a SourceText from the catalog —
// there is no pg_get_tabledef. Every identifier and literal inside the emitted statements is
// quoted by the server (format('%I'/'%L'), pg_get_constraintdef, pg_get_indexdef, pg_get_viewdef);
// this file authors no quoting of its own. Queries run sequentially against exec — the same
// single-connection rule describe() and getReadTarget() already document.
func buildDefinition(ctx context.Context, exec queryExec, segments []model.PathSegment, schema string, objectKind, objectName string) (model.ObjectDefinition, error) {
	info, err := getRelationInfo(ctx, exec, schema, objectName)
	if err != nil {
		return model.ObjectDefinition{}, err
	}

	m, err := fetchRelationMeta(ctx, exec, schema, objectName, info.OID)
	if err != nil {
		return model.ObjectDefinition{}, err
	}

	keyword := relationKeyword[objectKind]
	var statements []string
	var constraintMetas []model.ConstraintMeta
	var forkNotes []string

	if objectKind == "table" {
		statements, constraintMetas, forkNotes, err = buildTableStatements(ctx, exec, info.OID, m.qname, m)
	} else {
		statements, forkNotes, err = buildViewStatements(ctx, exec, info.OID, m.qname, schema, objectKind, objectName, keyword, m)
	}
	if err != nil {
		return model.ObjectDefinition{}, err
	}
	notes := make([]string, 0, 1+len(forkNotes))
	notes = append(notes, composedScopeNote)
	notes = append(notes, forkNotes...)

	relComment, columnComments, err := fetchComments(ctx, exec, info.OID, m.qname, keyword)
	if err != nil {
		return model.ObjectDefinition{}, err
	}
	if relComment != nil {
		statements = append(statements, *relComment)
	}
	statements = append(statements, columnComments...)

	return model.ObjectDefinition{
		Path: model.EncodePath(segments), Kind: objectKind, QualifiedName: schema + "." + objectName,
		Statements: statements, Language: "sql", Origin: "composed", Notes: notes,
		Constraints: constraintMetas, DocumentSchema: nil, Sections: []model.DefinitionSection{},
		GeneratedAt: time.Now().UTC().Format(time.RFC3339Nano),
	}, nil
}
