import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ControlSnapshot, PortSnapshot } from './types';

export const FIXTURE_WRITE_ENV = 'KIRA_IPC_FIXTURES';

/** `KIRA_IPC_FIXTURES=write` rewrites the adapter's fixture module from real backend responses
 *  (P50 D5) — a fixture is captured from a real run, never hand-written; F7's incident (a
 *  hand-written tree node using the wrong `path` shape, silently rendered rather than rejected)
 *  is the whole reason this exists. */
export function isFixtureWriteMode(): boolean {
  return process.env[FIXTURE_WRITE_ENV] === 'write';
}

/** `import.meta.url`/`__dirname` both resolve to `out/tests/ipc/…` once a spec is esbuild-bundled
 *  (scripts/run-ipc-backend.sh), not to its source location under `tests/ipc/<adapter>/` — so the
 *  fixture path is derived from `process.cwd()` instead, which the runner script always sets to
 *  the repo root before invoking `electron`. */
export function fixturePathFor(adapterName: string): string {
  return resolve(process.cwd(), 'tests/ipc', adapterName, `${adapterName}.fixture.ts`);
}

export function writeFixtureModule(
  filePath: string,
  adapterName: string,
  controlSnapshots: readonly ControlSnapshot[],
  portSnapshots: readonly PortSnapshot[],
): void {
  const header =
    `// Generated by tests/ipc/${adapterName}/${adapterName}.backend.spec.ts with\n` +
    `// KIRA_IPC_FIXTURES=write — do not hand-edit (P50 D5). The backend spec asserts every run's\n` +
    `// real response against this file; the frontend spec mocks the IPC layer with the exact same\n` +
    `// file. That is the split's anti-drift rule: a frontend spec cannot mock a shape the backend\n` +
    `// has stopped producing without this file's own backend assertion failing first.\n` +
    `import type { ControlSnapshot, PortSnapshot } from '../support/types';\n`;
  const body =
    `\nexport const controlSnapshots: ControlSnapshot[] = ${JSON.stringify(controlSnapshots, null, 2)};\n` +
    `\nexport const portSnapshots: PortSnapshot[] = ${JSON.stringify(portSnapshots, null, 2)};\n`;
  writeFileSync(filePath, header + body);
}
