// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CacheStats struct {
	_tab flatbuffers.Table
}

func GetRootAsCacheStats(buf []byte, offset flatbuffers.UOffsetT) *CacheStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CacheStats{}
	x.Init(buf, n+offset)
	return x
}

func FinishCacheStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCacheStats(buf []byte, offset flatbuffers.UOffsetT) *CacheStats {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CacheStats{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCacheStatsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CacheStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CacheStats) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CacheStats) L2Bytes() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CacheStats) MutateL2Bytes(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *CacheStats) L2BudgetBytes() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CacheStats) MutateL2BudgetBytes(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *CacheStats) L2Entries() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CacheStats) MutateL2Entries(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *CacheStats) L2Hits() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CacheStats) MutateL2Hits(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *CacheStats) L2Misses() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CacheStats) MutateL2Misses(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *CacheStats) L3Entries() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CacheStats) MutateL3Entries(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func CacheStatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func CacheStatsAddL2Bytes(builder *flatbuffers.Builder, l2Bytes float64) {
	builder.PrependFloat64Slot(0, l2Bytes, 0.0)
}
func CacheStatsAddL2BudgetBytes(builder *flatbuffers.Builder, l2BudgetBytes float64) {
	builder.PrependFloat64Slot(1, l2BudgetBytes, 0.0)
}
func CacheStatsAddL2Entries(builder *flatbuffers.Builder, l2Entries int32) {
	builder.PrependInt32Slot(2, l2Entries, 0)
}
func CacheStatsAddL2Hits(builder *flatbuffers.Builder, l2Hits int32) {
	builder.PrependInt32Slot(3, l2Hits, 0)
}
func CacheStatsAddL2Misses(builder *flatbuffers.Builder, l2Misses int32) {
	builder.PrependInt32Slot(4, l2Misses, 0)
}
func CacheStatsAddL3Entries(builder *flatbuffers.Builder, l3Entries int32) {
	builder.PrependInt32Slot(5, l3Entries, 0)
}
func CacheStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
