// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ColumnDescriptor struct {
	_tab flatbuffers.Table
}

func GetRootAsColumnDescriptor(buf []byte, offset flatbuffers.UOffsetT) *ColumnDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ColumnDescriptor{}
	x.Init(buf, n+offset)
	return x
}

func FinishColumnDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsColumnDescriptor(buf []byte, offset flatbuffers.UOffsetT) *ColumnDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ColumnDescriptor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedColumnDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ColumnDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColumnDescriptor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ColumnDescriptor) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ColumnDescriptor) DataType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ColumnDescriptor) TypeClass() TypeClass {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return TypeClass(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ColumnDescriptor) MutateTypeClass(n TypeClass) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *ColumnDescriptor) Nullable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ColumnDescriptor) MutateNullable(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *ColumnDescriptor) IsPrimaryKey() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ColumnDescriptor) MutateIsPrimaryKey(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ColumnDescriptor) Generated() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ColumnDescriptor) MutateGenerated(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func ColumnDescriptorStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ColumnDescriptorAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ColumnDescriptorAddDataType(builder *flatbuffers.Builder, dataType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dataType), 0)
}
func ColumnDescriptorAddTypeClass(builder *flatbuffers.Builder, typeClass TypeClass) {
	builder.PrependByteSlot(2, byte(typeClass), 0)
}
func ColumnDescriptorAddNullable(builder *flatbuffers.Builder, nullable bool) {
	builder.PrependBoolSlot(3, nullable, false)
}
func ColumnDescriptorAddIsPrimaryKey(builder *flatbuffers.Builder, isPrimaryKey bool) {
	builder.PrependBoolSlot(4, isPrimaryKey, false)
}
func ColumnDescriptorAddGenerated(builder *flatbuffers.Builder, generated bool) {
	builder.PrependBoolSlot(5, generated, false)
}
func ColumnDescriptorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
