// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CountResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCountResponse(buf []byte, offset flatbuffers.UOffsetT) *CountResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CountResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCountResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCountResponse(buf []byte, offset flatbuffers.UOffsetT) *CountResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CountResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCountResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CountResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CountResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CountResponse) Value() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CountResponse) MutateValue(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *CountResponse) Exact() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CountResponse) MutateExact(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *CountResponse) At() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CountResponse) MutateAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *CountResponse) Stale() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CountResponse) MutateStale(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *CountResponse) Source() Source {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return Source(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CountResponse) MutateSource(n Source) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func CountResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func CountResponseAddValue(builder *flatbuffers.Builder, value float64) {
	builder.PrependFloat64Slot(0, value, 0.0)
}
func CountResponseAddExact(builder *flatbuffers.Builder, exact bool) {
	builder.PrependBoolSlot(1, exact, false)
}
func CountResponseAddAt(builder *flatbuffers.Builder, at float64) {
	builder.PrependFloat64Slot(2, at, 0.0)
}
func CountResponseAddStale(builder *flatbuffers.Builder, stale bool) {
	builder.PrependBoolSlot(3, stale, false)
}
func CountResponseAddSource(builder *flatbuffers.Builder, source Source) {
	builder.PrependByteSlot(4, byte(source), 0)
}
func CountResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
