// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DocumentPage struct {
	_tab flatbuffers.Table
}

func GetRootAsDocumentPage(buf []byte, offset flatbuffers.UOffsetT) *DocumentPage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DocumentPage{}
	x.Init(buf, n+offset)
	return x
}

func FinishDocumentPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDocumentPage(buf []byte, offset flatbuffers.UOffsetT) *DocumentPage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DocumentPage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDocumentPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DocumentPage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DocumentPage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DocumentPage) Position(obj *PagePosition) *PagePosition {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PagePosition)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DocumentPage) Ids(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DocumentPage) Bodies(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DocumentPage) RowCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DocumentPage) MutateRowCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *DocumentPage) ByteSize() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DocumentPage) MutateByteSize(n float64) bool {
	return rcv._tab.MutateFloat64Slot(12, n)
}

func (rcv *DocumentPage) FetchedAt() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DocumentPage) MutateFetchedAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func DocumentPageStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func DocumentPageAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(position), 0)
}
func DocumentPageAddIds(builder *flatbuffers.Builder, ids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ids), 0)
}
func DocumentPageAddBodies(builder *flatbuffers.Builder, bodies flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bodies), 0)
}
func DocumentPageAddRowCount(builder *flatbuffers.Builder, rowCount int32) {
	builder.PrependInt32Slot(3, rowCount, 0)
}
func DocumentPageAddByteSize(builder *flatbuffers.Builder, byteSize float64) {
	builder.PrependFloat64Slot(4, byteSize, 0.0)
}
func DocumentPageAddFetchedAt(builder *flatbuffers.Builder, fetchedAt float64) {
	builder.PrependFloat64Slot(5, fetchedAt, 0.0)
}
func DocumentPageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
