// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EmptyResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsEmptyResponse(buf []byte, offset flatbuffers.UOffsetT) *EmptyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EmptyResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishEmptyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEmptyResponse(buf []byte, offset flatbuffers.UOffsetT) *EmptyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EmptyResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEmptyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EmptyResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EmptyResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func EmptyResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EmptyResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
