// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExecuteResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsExecuteResponse(buf []byte, offset flatbuffers.UOffsetT) *ExecuteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExecuteResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishExecuteResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExecuteResponse(buf []byte, offset flatbuffers.UOffsetT) *ExecuteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExecuteResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExecuteResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExecuteResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExecuteResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExecuteResponse) Pages(obj *Page, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ExecuteResponse) PagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ExecuteResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ExecuteResponseAddPages(builder *flatbuffers.Builder, pages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pages), 0)
}
func ExecuteResponseStartPagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ExecuteResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
