// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type FrameKind byte

const (
	FrameKindres FrameKind = 0
	FrameKindevt FrameKind = 1
)

var EnumNamesFrameKind = map[FrameKind]string{
	FrameKindres: "res",
	FrameKindevt: "evt",
}

var EnumValuesFrameKind = map[string]FrameKind{
	"res": FrameKindres,
	"evt": FrameKindevt,
}

func (v FrameKind) String() string {
	if s, ok := EnumNamesFrameKind[v]; ok {
		return s
	}
	return "FrameKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
