// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyValuePage struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyValuePage(buf []byte, offset flatbuffers.UOffsetT) *KeyValuePage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyValuePage{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyValuePageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyValuePage(buf []byte, offset flatbuffers.UOffsetT) *KeyValuePage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyValuePage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyValuePageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyValuePage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyValuePage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyValuePage) Position(obj *PagePosition) *PagePosition {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PagePosition)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *KeyValuePage) RedisType() RedisType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return RedisType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *KeyValuePage) MutateRedisType(n RedisType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *KeyValuePage) TtlMs() *float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetFloat64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *KeyValuePage) MutateTtlMs(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *KeyValuePage) MemoryBytes() *float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetFloat64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *KeyValuePage) MutateMemoryBytes(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *KeyValuePage) Fields(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *KeyValuePage) Values(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *KeyValuePage) RowCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyValuePage) MutateRowCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *KeyValuePage) ByteSize() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *KeyValuePage) MutateByteSize(n float64) bool {
	return rcv._tab.MutateFloat64Slot(18, n)
}

func (rcv *KeyValuePage) FetchedAt() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *KeyValuePage) MutateFetchedAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(20, n)
}

func KeyValuePageStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func KeyValuePageAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(position), 0)
}
func KeyValuePageAddRedisType(builder *flatbuffers.Builder, redisType RedisType) {
	builder.PrependByteSlot(1, byte(redisType), 0)
}
func KeyValuePageAddTtlMs(builder *flatbuffers.Builder, ttlMs float64) {
	builder.PrependFloat64(ttlMs)
	builder.Slot(2)
}
func KeyValuePageAddMemoryBytes(builder *flatbuffers.Builder, memoryBytes float64) {
	builder.PrependFloat64(memoryBytes)
	builder.Slot(3)
}
func KeyValuePageAddFields(builder *flatbuffers.Builder, fields flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(fields), 0)
}
func KeyValuePageAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(values), 0)
}
func KeyValuePageAddRowCount(builder *flatbuffers.Builder, rowCount int32) {
	builder.PrependInt32Slot(6, rowCount, 0)
}
func KeyValuePageAddByteSize(builder *flatbuffers.Builder, byteSize float64) {
	builder.PrependFloat64Slot(7, byteSize, 0.0)
}
func KeyValuePageAddFetchedAt(builder *flatbuffers.Builder, fetchedAt float64) {
	builder.PrependFloat64Slot(8, fetchedAt, 0.0)
}
func KeyValuePageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
