// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MutateResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsMutateResponse(buf []byte, offset flatbuffers.UOffsetT) *MutateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MutateResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishMutateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMutateResponse(buf []byte, offset flatbuffers.UOffsetT) *MutateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MutateResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMutateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MutateResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MutateResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MutateResponse) AffectedRows() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MutateResponse) MutateAffectedRows(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func MutateResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MutateResponseAddAffectedRows(builder *flatbuffers.Builder, affectedRows int32) {
	builder.PrependInt32Slot(0, affectedRows, 0)
}
func MutateResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
