// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ObjectDownloadResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsObjectDownloadResponse(buf []byte, offset flatbuffers.UOffsetT) *ObjectDownloadResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ObjectDownloadResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishObjectDownloadResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsObjectDownloadResponse(buf []byte, offset flatbuffers.UOffsetT) *ObjectDownloadResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ObjectDownloadResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedObjectDownloadResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ObjectDownloadResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ObjectDownloadResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ObjectDownloadResponse) Bytes() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ObjectDownloadResponse) MutateBytes(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func ObjectDownloadResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ObjectDownloadResponseAddBytes(builder *flatbuffers.Builder, bytes float64) {
	builder.PrependFloat64Slot(0, bytes, 0.0)
}
func ObjectDownloadResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
