// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PagePosition struct {
	_tab flatbuffers.Table
}

func GetRootAsPagePosition(buf []byte, offset flatbuffers.UOffsetT) *PagePosition {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PagePosition{}
	x.Init(buf, n+offset)
	return x
}

func FinishPagePositionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPagePosition(buf []byte, offset flatbuffers.UOffsetT) *PagePosition {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PagePosition{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPagePositionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PagePosition) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PagePosition) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PagePosition) Offset() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *PagePosition) MutateOffset(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PagePosition) PageSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PagePosition) MutatePageSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *PagePosition) HasMore() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PagePosition) MutateHasMore(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *PagePosition) NextToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PagePosition) PrevToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PagePosition) Strategy() Strategy {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return Strategy(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PagePosition) MutateStrategy(n Strategy) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

func PagePositionStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func PagePositionAddOffset(builder *flatbuffers.Builder, offset int32) {
	builder.PrependInt32(offset)
	builder.Slot(0)
}
func PagePositionAddPageSize(builder *flatbuffers.Builder, pageSize int32) {
	builder.PrependInt32Slot(1, pageSize, 0)
}
func PagePositionAddHasMore(builder *flatbuffers.Builder, hasMore bool) {
	builder.PrependBoolSlot(2, hasMore, false)
}
func PagePositionAddNextToken(builder *flatbuffers.Builder, nextToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(nextToken), 0)
}
func PagePositionAddPrevToken(builder *flatbuffers.Builder, prevToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(prevToken), 0)
}
func PagePositionAddStrategy(builder *flatbuffers.Builder, strategy Strategy) {
	builder.PrependByteSlot(5, byte(strategy), 0)
}
func PagePositionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
