// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Page struct {
	_tab flatbuffers.Table
}

func GetRootAsPage(buf []byte, offset flatbuffers.UOffsetT) *Page {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Page{}
	x.Init(buf, n+offset)
	return x
}

func FinishPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPage(buf []byte, offset flatbuffers.UOffsetT) *Page {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Page{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Page) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Page) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Page) BodyType() PageBody {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return PageBody(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Page) MutateBodyType(n PageBody) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Page) Body(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PageAddBodyType(builder *flatbuffers.Builder, bodyType PageBody) {
	builder.PrependByteSlot(0, byte(bodyType), 0)
}
func PageAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(body), 0)
}
func PageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
