// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type PageBody byte

const (
	PageBodyNONE         PageBody = 0
	PageBodyTabularPage  PageBody = 1
	PageBodyDocumentPage PageBody = 2
	PageBodyKeyValuePage PageBody = 3
	PageBodyStreamPage   PageBody = 4
)

var EnumNamesPageBody = map[PageBody]string{
	PageBodyNONE:         "NONE",
	PageBodyTabularPage:  "TabularPage",
	PageBodyDocumentPage: "DocumentPage",
	PageBodyKeyValuePage: "KeyValuePage",
	PageBodyStreamPage:   "StreamPage",
}

var EnumValuesPageBody = map[string]PageBody{
	"NONE":         PageBodyNONE,
	"TabularPage":  PageBodyTabularPage,
	"DocumentPage": PageBodyDocumentPage,
	"KeyValuePage": PageBodyKeyValuePage,
	"StreamPage":   PageBodyStreamPage,
}

func (v PageBody) String() string {
	if s, ok := EnumNamesPageBody[v]; ok {
		return s
	}
	return "PageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
