// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type Payload byte

const (
	PayloadNONE                   Payload = 0
	PayloadReadResponse           Payload = 1
	PayloadCountResponse          Payload = 2
	PayloadPreviewResponse        Payload = 3
	PayloadMutateResponse         Payload = 4
	PayloadExecuteResponse        Payload = 5
	PayloadObjectDownloadResponse Payload = 6
	PayloadPingPayload            Payload = 7
	PayloadCacheStats             Payload = 8
	PayloadEmptyResponse          Payload = 9
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:                   "NONE",
	PayloadReadResponse:           "ReadResponse",
	PayloadCountResponse:          "CountResponse",
	PayloadPreviewResponse:        "PreviewResponse",
	PayloadMutateResponse:         "MutateResponse",
	PayloadExecuteResponse:        "ExecuteResponse",
	PayloadObjectDownloadResponse: "ObjectDownloadResponse",
	PayloadPingPayload:            "PingPayload",
	PayloadCacheStats:             "CacheStats",
	PayloadEmptyResponse:          "EmptyResponse",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":                   PayloadNONE,
	"ReadResponse":           PayloadReadResponse,
	"CountResponse":          PayloadCountResponse,
	"PreviewResponse":        PayloadPreviewResponse,
	"MutateResponse":         PayloadMutateResponse,
	"ExecuteResponse":        PayloadExecuteResponse,
	"ObjectDownloadResponse": PayloadObjectDownloadResponse,
	"PingPayload":            PayloadPingPayload,
	"CacheStats":             PayloadCacheStats,
	"EmptyResponse":          PayloadEmptyResponse,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
