// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PingPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsPingPayload(buf []byte, offset flatbuffers.UOffsetT) *PingPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PingPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishPingPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPingPayload(buf []byte, offset flatbuffers.UOffsetT) *PingPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PingPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPingPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PingPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PingPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PingPayload) Pong() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PingPayload) MutatePong(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *PingPayload) EnginePid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PingPayload) MutateEnginePid(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *PingPayload) At() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PingPayload) MutateAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func PingPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PingPayloadAddPong(builder *flatbuffers.Builder, pong bool) {
	builder.PrependBoolSlot(0, pong, false)
}
func PingPayloadAddEnginePid(builder *flatbuffers.Builder, enginePid int32) {
	builder.PrependInt32Slot(1, enginePid, 0)
}
func PingPayloadAddAt(builder *flatbuffers.Builder, at float64) {
	builder.PrependFloat64Slot(2, at, 0.0)
}
func PingPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
