// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PreviewResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPreviewResponse(buf []byte, offset flatbuffers.UOffsetT) *PreviewResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PreviewResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPreviewResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPreviewResponse(buf []byte, offset flatbuffers.UOffsetT) *PreviewResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PreviewResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPreviewResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PreviewResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PreviewResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PreviewResponse) Statements(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *PreviewResponse) StatementsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PreviewResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PreviewResponseAddStatements(builder *flatbuffers.Builder, statements flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(statements), 0)
}
func PreviewResponseStartStatementsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PreviewResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
