// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReadResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsReadResponse(buf []byte, offset flatbuffers.UOffsetT) *ReadResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReadResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishReadResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReadResponse(buf []byte, offset flatbuffers.UOffsetT) *ReadResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReadResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReadResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReadResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReadResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReadResponse) Page(obj *Page) *Page {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Page)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ReadResponse) Source() Source {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Source(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ReadResponse) MutateSource(n Source) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func ReadResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReadResponseAddPage(builder *flatbuffers.Builder, page flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(page), 0)
}
func ReadResponseAddSource(builder *flatbuffers.Builder, source Source) {
	builder.PrependByteSlot(1, byte(source), 0)
}
func ReadResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
