// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type RedisType byte

const (
	RedisTypestring_ RedisType = 0
	RedisTypehash    RedisType = 1
	RedisTypelist    RedisType = 2
	RedisTypeset_    RedisType = 3
	RedisTypezset    RedisType = 4
	RedisTypestream  RedisType = 5
	RedisTypeobject  RedisType = 6
)

var EnumNamesRedisType = map[RedisType]string{
	RedisTypestring_: "string_",
	RedisTypehash:    "hash",
	RedisTypelist:    "list",
	RedisTypeset_:    "set_",
	RedisTypezset:    "zset",
	RedisTypestream:  "stream",
	RedisTypeobject:  "object",
}

var EnumValuesRedisType = map[string]RedisType{
	"string_": RedisTypestring_,
	"hash":    RedisTypehash,
	"list":    RedisTypelist,
	"set_":    RedisTypeset_,
	"zset":    RedisTypezset,
	"stream":  RedisTypestream,
	"object":  RedisTypeobject,
}

func (v RedisType) String() string {
	if s, ok := EnumNamesRedisType[v]; ok {
		return s
	}
	return "RedisType(" + strconv.FormatInt(int64(v), 10) + ")"
}
