// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type Source byte

const (
	Sourcecache  Source = 0
	Sourceserver Source = 1
)

var EnumNamesSource = map[Source]string{
	Sourcecache:  "cache",
	Sourceserver: "server",
}

var EnumValuesSource = map[string]Source{
	"cache":  Sourcecache,
	"server": Sourceserver,
}

func (v Source) String() string {
	if s, ok := EnumNamesSource[v]; ok {
		return s
	}
	return "Source(" + strconv.FormatInt(int64(v), 10) + ")"
}
