// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type Strategy byte

const (
	Strategykeyset       Strategy = 0
	Strategyoffset       Strategy = 1
	Strategycursor       Strategy = 2
	StrategyoffsetWindow Strategy = 3
	Strategybatch        Strategy = 4
)

var EnumNamesStrategy = map[Strategy]string{
	Strategykeyset:       "keyset",
	Strategyoffset:       "offset",
	Strategycursor:       "cursor",
	StrategyoffsetWindow: "offsetWindow",
	Strategybatch:        "batch",
}

var EnumValuesStrategy = map[string]Strategy{
	"keyset":       Strategykeyset,
	"offset":       Strategyoffset,
	"cursor":       Strategycursor,
	"offsetWindow": StrategyoffsetWindow,
	"batch":        Strategybatch,
}

func (v Strategy) String() string {
	if s, ok := EnumNamesStrategy[v]; ok {
		return s
	}
	return "Strategy(" + strconv.FormatInt(int64(v), 10) + ")"
}
