// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamPage struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamPage(buf []byte, offset flatbuffers.UOffsetT) *StreamPage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamPage{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamPage(buf []byte, offset flatbuffers.UOffsetT) *StreamPage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamPage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamPage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamPage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamPage) Position(obj *PagePosition) *PagePosition {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PagePosition)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) Keys(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) Headers(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) Attrs(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) Timestamps(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) Bodies(obj *Chunk) *Chunk {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Chunk)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *StreamPage) RowCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamPage) MutateRowCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *StreamPage) ByteSize() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StreamPage) MutateByteSize(n float64) bool {
	return rcv._tab.MutateFloat64Slot(18, n)
}

func (rcv *StreamPage) FetchedAt() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StreamPage) MutateFetchedAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(20, n)
}

func (rcv *StreamPage) VisibilityTimeoutSeconds() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *StreamPage) MutateVisibilityTimeoutSeconds(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func StreamPageStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func StreamPageAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(position), 0)
}
func StreamPageAddKeys(builder *flatbuffers.Builder, keys flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keys), 0)
}
func StreamPageAddHeaders(builder *flatbuffers.Builder, headers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(headers), 0)
}
func StreamPageAddAttrs(builder *flatbuffers.Builder, attrs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(attrs), 0)
}
func StreamPageAddTimestamps(builder *flatbuffers.Builder, timestamps flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(timestamps), 0)
}
func StreamPageAddBodies(builder *flatbuffers.Builder, bodies flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(bodies), 0)
}
func StreamPageAddRowCount(builder *flatbuffers.Builder, rowCount int32) {
	builder.PrependInt32Slot(6, rowCount, 0)
}
func StreamPageAddByteSize(builder *flatbuffers.Builder, byteSize float64) {
	builder.PrependFloat64Slot(7, byteSize, 0.0)
}
func StreamPageAddFetchedAt(builder *flatbuffers.Builder, fetchedAt float64) {
	builder.PrependFloat64Slot(8, fetchedAt, 0.0)
}
func StreamPageAddVisibilityTimeoutSeconds(builder *flatbuffers.Builder, visibilityTimeoutSeconds int32) {
	builder.PrependInt32(visibilityTimeoutSeconds)
	builder.Slot(9)
}
func StreamPageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
