// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TabularPage struct {
	_tab flatbuffers.Table
}

func GetRootAsTabularPage(buf []byte, offset flatbuffers.UOffsetT) *TabularPage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TabularPage{}
	x.Init(buf, n+offset)
	return x
}

func FinishTabularPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTabularPage(buf []byte, offset flatbuffers.UOffsetT) *TabularPage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TabularPage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTabularPageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TabularPage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TabularPage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TabularPage) Columns(obj *ColumnDescriptor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TabularPage) ColumnsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TabularPage) RowCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TabularPage) MutateRowCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TabularPage) Chunks(obj *Chunk, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TabularPage) ChunksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TabularPage) Position(obj *PagePosition) *PagePosition {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PagePosition)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TabularPage) TruncatedCells() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TabularPage) MutateTruncatedCells(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *TabularPage) ByteSize() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TabularPage) MutateByteSize(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func (rcv *TabularPage) FetchedAt() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TabularPage) MutateFetchedAt(n float64) bool {
	return rcv._tab.MutateFloat64Slot(16, n)
}

func TabularPageStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func TabularPageAddColumns(builder *flatbuffers.Builder, columns flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(columns), 0)
}
func TabularPageStartColumnsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TabularPageAddRowCount(builder *flatbuffers.Builder, rowCount int32) {
	builder.PrependInt32Slot(1, rowCount, 0)
}
func TabularPageAddChunks(builder *flatbuffers.Builder, chunks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(chunks), 0)
}
func TabularPageStartChunksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TabularPageAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(position), 0)
}
func TabularPageAddTruncatedCells(builder *flatbuffers.Builder, truncatedCells int32) {
	builder.PrependInt32Slot(4, truncatedCells, 0)
}
func TabularPageAddByteSize(builder *flatbuffers.Builder, byteSize float64) {
	builder.PrependFloat64Slot(5, byteSize, 0.0)
}
func TabularPageAddFetchedAt(builder *flatbuffers.Builder, fetchedAt float64) {
	builder.PrependFloat64Slot(6, fetchedAt, 0.0)
}
func TabularPageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
