// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type TypeClass byte

const (
	TypeClassnumber   TypeClass = 0
	TypeClasstext     TypeClass = 1
	TypeClassboolean  TypeClass = 2
	TypeClasstemporal TypeClass = 3
	TypeClassbinary   TypeClass = 4
	TypeClassjson     TypeClass = 5
	TypeClassother    TypeClass = 6
)

var EnumNamesTypeClass = map[TypeClass]string{
	TypeClassnumber:   "number",
	TypeClasstext:     "text",
	TypeClassboolean:  "boolean",
	TypeClasstemporal: "temporal",
	TypeClassbinary:   "binary",
	TypeClassjson:     "json",
	TypeClassother:    "other",
}

var EnumValuesTypeClass = map[string]TypeClass{
	"number":   TypeClassnumber,
	"text":     TypeClasstext,
	"boolean":  TypeClassboolean,
	"temporal": TypeClasstemporal,
	"binary":   TypeClassbinary,
	"json":     TypeClassjson,
	"other":    TypeClassother,
}

func (v TypeClass) String() string {
	if s, ok := EnumNamesTypeClass[v]; ok {
		return s
	}
	return "TypeClass(" + strconv.FormatInt(int64(v), 10) + ")"
}
